<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-Carbon_inventory_platform-f19a92ee-d2ab-4dcf-b9e2-42c55370b2e7</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Data\Migrations\**" />
    <Compile Remove="Models\NewFolder1\**" />
    <Compile Remove="Models\NewFolder\**" />
    <Compile Remove="Views\Area\**" />
    <Content Remove="Data\Migrations\**" />
    <Content Remove="Models\NewFolder1\**" />
    <Content Remove="Models\NewFolder\**" />
    <Content Remove="Views\Area\**" />
    <EmbeddedResource Remove="Data\Migrations\**" />
    <EmbeddedResource Remove="Models\NewFolder1\**" />
    <EmbeddedResource Remove="Models\NewFolder\**" />
    <EmbeddedResource Remove="Views\Area\**" />
    <None Remove="Data\Migrations\**" />
    <None Remove="Models\NewFolder1\**" />
    <None Remove="Models\NewFolder\**" />
    <None Remove="Views\Area\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="DocX" Version="2.5.0" />
    <PackageReference Include="ElectronNET.API" Version="23.6.2" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="7.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="7.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="7.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="7.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="7.0.15">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Office.Interop.Word" Version="15.0.4797.1004" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="7.0.11" />
  </ItemGroup>
  <ItemGroup>
    <Content Update="Views\Home\Index.cshtml">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <Content Update="electron.manifest.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="wwwroot\output\" />
  </ItemGroup>
</Project>