// <auto-generated />
using System;
using Carbon_inventory_platform.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Carbon_inventory_platform.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230901065030_0.0.1-6")]
    partial class _0016
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AreaDevice", b =>
                {
                    b.Property<Guid>("AreaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AreasId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AreaId", "AreasId");

                    b.HasIndex("AreasId");

                    b.ToTable("AreaDevice");
                });

            modelBuilder.Entity("Carbon_inventory_platform.Models.Area", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("PostalCode")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.Property<byte>("isDeleted")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("Carbon_inventory_platform.Models.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte>("isDeleted")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Carbon_inventory_platform.Models.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AreaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssetNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("CH4")
                        .HasColumnType("bit");

                    b.Property<bool>("CO2")
                        .HasColumnType("bit");

                    b.Property<int>("Correction")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dept")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("HFCS")
                        .HasColumnType("bit");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("N2O")
                        .HasColumnType("bit");

                    b.Property<bool>("NF3")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<float>("Num")
                        .HasColumnType("real");

                    b.Property<bool>("PFCS")
                        .HasColumnType("bit");

                    b.Property<string>("Provess")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("SF6")
                        .HasColumnType("bit");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte>("isDeleted")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("Carbon_inventory_platform.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float?>("CH4CEF")
                        .HasColumnType("real");

                    b.Property<float?>("CH4ULL")
                        .HasColumnType("real");

                    b.Property<float?>("CH4UUL")
                        .HasColumnType("real");

                    b.Property<float?>("CO2CEF")
                        .HasColumnType("real");

                    b.Property<float?>("CO2ULL")
                        .HasColumnType("real");

                    b.Property<float?>("CO2UUL")
                        .HasColumnType("real");

                    b.Property<string>("EmissionPattern")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<float?>("N2OCEF")
                        .HasColumnType("real");

                    b.Property<float?>("N2OULL")
                        .HasColumnType("real");

                    b.Property<float?>("N2OUUL")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Materials");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CH4CEF = 2.5E-05f,
                            CH4ULL = 0.7f,
                            CH4UUL = 2f,
                            CO2CEF = 2.33286f,
                            CO2ULL = 0.077167f,
                            CO2UUL = 0.067653f,
                            EmissionPattern = "固定",
                            N2OCEF = 3.7E-05f,
                            N2OULL = 0.666667f,
                            N2OUUL = 2.333333f,
                            Name = "自產煤",
                            Scope = "範疇1",
                            Unit = "Kg",
                            Year = 0
                        },
                        new
                        {
                            Id = 2,
                            CH4CEF = 2.8E-05f,
                            CH4ULL = 0.7f,
                            CH4UUL = 2f,
                            CO2CEF = 2.693285f,
                            CO2ULL = 0.077167f,
                            CO2UUL = 0.067653f,
                            EmissionPattern = "固定",
                            N2OCEF = 4.3E-05f,
                            N2OULL = 0.666667f,
                            N2OUUL = 2.333333f,
                            Name = "原料煤",
                            Scope = "範疇1",
                            Unit = "Kg",
                            Year = 0
                        },
                        new
                        {
                            Id = 3,
                            CH4CEF = 2.5E-05f,
                            CH4ULL = 0.7f,
                            CH4UUL = 2f,
                            CO2CEF = 2.408113f,
                            CO2ULL = 0.077167f,
                            CO2UUL = 0.067653f,
                            EmissionPattern = "固定",
                            N2OCEF = 3.8E-05f,
                            N2OULL = 0.666667f,
                            N2OUUL = 2.333333f,
                            Name = "燃料煤",
                            Scope = "範疇1",
                            Unit = "Kg",
                            Year = 0
                        },
                        new
                        {
                            Id = 4,
                            CH4CEF = 3E-05f,
                            CH4ULL = 0.7f,
                            CH4UUL = 2f,
                            CO2CEF = 2.922093f,
                            CO2ULL = 0.03764f,
                            CO2UUL = 0.027467f,
                            EmissionPattern = "固定",
                            N2OCEF = 4.5E-05f,
                            N2OULL = 0.666667f,
                            N2OUUL = 2.333333f,
                            Name = "無煙煤",
                            Scope = "範疇1",
                            Unit = "Kg",
                            Year = 0
                        },
                        new
                        {
                            Id = 5,
                            CH4CEF = 2.8E-05f,
                            CH4ULL = 0.7f,
                            CH4UUL = 2f,
                            CO2CEF = 2.693285f,
                            CO2ULL = 0.077167f,
                            CO2UUL = 0.067653f,
                            EmissionPattern = "固定",
                            N2OCEF = 4.3E-05f,
                            N2OULL = 0.666667f,
                            N2OUUL = 2.333333f,
                            Name = "焦煤",
                            Scope = "範疇1",
                            Unit = "Kg",
                            Year = 0
                        },
                        new
                        {
                            Id = 6,
                            CH4CEF = 2.5E-05f,
                            CH4ULL = 0.7f,
                            CH4UUL = 2f,
                            CO2CEF = 2.408113f,
                            CO2ULL = 0.053911f,
                            CO2UUL = 0.053911f,
                            EmissionPattern = "固定",
                            N2OCEF = 3.8E-05f,
                            N2OULL = 0.666667f,
                            N2OUUL = 2.333333f,
                            Name = "煙煤",
                            Scope = "範疇1",
                            Unit = "Kg",
                            Year = 0
                        },
                        new
                        {
                            Id = 7,
                            CH4CEF = 2.1E-05f,
                            CH4ULL = 0.7f,
                            CH4UUL = 2f,
                            CO2CEF = 1.971522f,
                            CO2ULL = 0.034339f,
                            CO2UUL = 0.040583f,
                            EmissionPattern = "固定",
                            N2OCEF = 3.1E-05f,
                            N2OULL = 0.666667f,
                            N2OUUL = 2.333333f,
                            Name = "亞煙煤(發電)",
                            Scope = "範疇1",
                            Unit = "Kg",
                            Year = 0
                        },
                        new
                        {
                            Id = 8,
                            CH4CEF = 2.3E-05f,
                            CH4ULL = 0.7f,
                            CH4UUL = 2f,
                            CO2CEF = 2.253168f,
                            CO2ULL = 0.034339f,
                            CO2UUL = 0.040583f,
                            EmissionPattern = "固定",
                            N2OCEF = 3.5E-05f,
                            N2OULL = 0.666667f,
                            N2OUUL = 2.333333f,
                            Name = "亞煙煤(其他)",
                            Scope = "範疇1",
                            Unit = "Kg",
                            Year = 0
                        },
                        new
                        {
                            Id = 9,
                            CH4CEF = 1.2E-05f,
                            CH4ULL = 0.7f,
                            CH4UUL = 2f,
                            CO2CEF = 1.202633f,
                            CO2ULL = 0.1f,
                            CO2UUL = 0.138614f,
                            EmissionPattern = "固定",
                            N2OCEF = 1.8E-05f,
                            N2OULL = 0.666667f,
                            N2OUUL = 2.333333f,
                            Name = "褐煤",
                            Scope = "範疇1",
                            Unit = "Kg",
                            Year = 0
                        },
                        new
                        {
                            Id = 10,
                            CH4CEF = 9E-06f,
                            CH4ULL = 0.7f,
                            CH4UUL = 2f,
                            CO2CEF = 0.95287f,
                            CO2ULL = 0.157009f,
                            CO2UUL = 0.168224f,
                            EmissionPattern = "固定",
                            N2OCEF = 1.3E-05f,
                            N2OULL = 0.666667f,
                            N2OUUL = 2.333333f,
                            Name = "油頁岩",
                            Scope = "範疇1",
                            Unit = "Kg",
                            Year = 0
                        },
                        new
                        {
                            Id = 11,
                            CH4CEF = 1E-05f,
                            CH4ULL = 0.7f,
                            CH4UUL = 2f,
                            CO2CEF = 1.035387f,
                            CO2ULL = 0.056604f,
                            CO2UUL = 0.018868f,
                            EmissionPattern = "固定",
                            N2OCEF = 1.5E-05f,
                            N2OULL = 0.666667f,
                            N2OUUL = 2.333333f,
                            Name = "泥煤",
                            Scope = "範疇1",
                            Unit = "Kg",
                            Year = 0
                        },
                        new
                        {
                            Id = 12,
                            CH4CEF = 1.6E-05f,
                            CH4ULL = 0.7f,
                            CH4UUL = 2f,
                            CO2CEF = 1.551209f,
                            CO2ULL = 0.104615f,
                            CO2UUL = 0.117949f,
                            EmissionPattern = "固定",
                            N2OCEF = 2.4E-05f,
                            N2OULL = 0.666667f,
                            N2OUUL = 2.333333f,
                            Name = "煤球",
                            Scope = "範疇1",
                            Unit = "Kg",
                            Year = 0
                        },
                        new
                        {
                            Id = 13,
                            CH4CEF = 2.9E-05f,
                            CH4ULL = 0.7f,
                            CH4UUL = 2f,
                            CO2CEF = 3.135913f,
                            CO2ULL = 0.105607f,
                            CO2UUL = 0.11215f,
                            EmissionPattern = "固定",
                            N2OCEF = 4.4E-05f,
                            N2OULL = 0.666667f,
                            N2OUUL = 2.333333f,
                            Name = "焦炭",
                            Scope = "範疇1",
                            Unit = "Kg",
                            Year = 0
                        },
                        new
                        {
                            Id = 14,
                            CH4CEF = 0.000103f,
                            CH4ULL = 0.666667f,
                            CH4UUL = 2.333333f,
                            CO2CEF = 3.347347f,
                            CO2ULL = 0.149744f,
                            CO2UUL = 0.179487f,
                            EmissionPattern = "固定",
                            N2OCEF = 2.1E-05f,
                            N2OULL = 0.666667f,
                            N2OUUL = 2.333333f,
                            Name = "石油焦",
                            Scope = "範疇1",
                            Unit = "Kg",
                            Year = 0
                        },
                        new
                        {
                            Id = 15,
                            CH4CEF = 9.4E-05f,
                            CH4ULL = 0.666667f,
                            CH4UUL = 2.333333f,
                            CO2CEF = 2.19807f,
                            CO2ULL = 0.035714f,
                            CO2UUL = 0.042857f,
                            EmissionPattern = "固定",
                            N2OCEF = 1.9E-05f,
                            N2OULL = 0.666667f,
                            N2OUUL = 2.333333f,
                            Name = "航空汽油",
                            Scope = "範疇1",
                            Unit = "L",
                            Year = 0
                        },
                        new
                        {
                            Id = 16,
                            CH4CEF = 0.0001f,
                            CH4ULL = 0.666667f,
                            CH4UUL = 2.333333f,
                            CO2CEF = 2.39485f,
                            CO2ULL = 0.025175f,
                            CO2UUL = 0.040559f,
                            EmissionPattern = "固定",
                            N2OCEF = 2E-05f,
                            N2OULL = 0.666667f,
                            N2OUUL = 2.333333f,
                            Name = "航空燃油",
                            Scope = "範疇1",
                            Unit = "L",
                            Year = 0
                        },
                        new
                        {
                            Id = 17,
                            CH4CEF = 0.000113f,
                            CH4ULL = 0.666667f,
                            CH4UUL = 2.333333f,
                            CO2CEF = 2.762032f,
                            CO2ULL = 0.030014f,
                            CO2UUL = 0.030014f,
                            EmissionPattern = "固定",
                            N2OCEF = 2.3E-05f,
                            N2OULL = 0.666667f,
                            N2OUUL = 2.333333f,
                            Name = "原油",
                            Scope = "範疇1",
                            Unit = "L",
                            Year = 0
                        },
                        new
                        {
                            Id = 18,
                            CH4CEF = 8.3E-05f,
                            CH4ULL = 0.666667f,
                            CH4UUL = 2.333333f,
                            CO2CEF = 2.119027f,
                            CO2ULL = 0.1f,
                            CO2UUL = 0.109091f,
                            EmissionPattern = "固定",
                            N2OCEF = 1.7E-05f,
                            N2OULL = 0.666667f,
                            N2OUUL = 2.333333f,
                            Name = "奧里油",
                            Scope = "範疇1",
                            Unit = "Kg",
                            Year = 0
                        },
                        new
                        {
                            Id = 19,
                            CH4CEF = 0.000133f,
                            CH4ULL = 0.666667f,
                            CH4UUL = 2.333333f,
                            CO2CEF = 2.839525f,
                            CO2ULL = 0.0919f,
                            CO2UUL = 0.096573f,
                            EmissionPattern = "固定",
                            N2OCEF = 2.7E-05f,
                            N2OULL = 0.666667f,
                            N2OUUL = 2.333333f,
                            Name = "天然氣凝結油",
                            Scope = "範疇1",
                            Unit = "M3",
                            Year = 0
                        },
                        new
                        {
                            Id = 20,
                            CH4CEF = 0.000107f,
                            CH4ULL = 0.666667f,
                            CH4UUL = 2.333333f,
                            CO2CEF = 2.558763f,
                            CO2ULL = 0.015299f,
                            CO2UUL = 0.025035f,
                            EmissionPattern = "固定",
                            N2OCEF = 2.1E-05f,
                            N2OULL = 0.666667f,
                            N2OUUL = 2.333333f,
                            Name = "煤油",
                            Scope = "範疇1",
                            Unit = "L",
                            Year = 0
                        },
                        new
                        {
                            Id = 21,
                            CH4CEF = 0.000108f,
                            CH4ULL = 0.666667f,
                            CH4UUL = 2.333333f,
                            CO2CEF = 2.794563f,
                            CO2ULL = 0.075034f,
                            CO2UUL = 0.080491f,
                            EmissionPattern = "固定",
                            N2OCEF = 2.2E-05f,
                            N2OULL = 0.666667f,
                            N2OUUL = 2.333333f,
                            Name = "頁岩油",
                            Scope = "範疇1",
                            Unit = "Kg",
                            Year = 0
                        },
                        new
                        {
                            Id = 22,
                            CH4CEF = 0.000106f,
                            CH4ULL = 0.666667f,
                            CH4UUL = 2.333333f,
                            CO2CEF = 2.606032f,
                            CO2ULL = 0.020243f,
                            CO2UUL = 0.009447f,
                            EmissionPattern = "固定",
                            N2OCEF = 2.1E-05f,
                            N2OULL = 0.666667f,
                            N2OUUL = 2.333333f,
                            Name = "柴油",
                            Scope = "範疇1",
                            Unit = "L",
                            Year = 0
                        },
                        new
                        {
                            Id = 23,
                            CH4CEF = 9.8E-05f,
                            CH4ULL = 0.666667f,
                            CH4UUL = 2.333333f,
                            CO2CEF = 2.263133f,
                            CO2ULL = 0.025974f,
                            CO2UUL = 0.053391f,
                            EmissionPattern = "固定",
                            N2OCEF = 2E-05f,
                            N2OULL = 0.666667f,
                            N2OUUL = 2.333333f,
                            Name = "車用汽油",
                            Scope = "範疇1",
                            Unit = "L",
                            Year = 0
                        },
                        new
                        {
                            Id = 24,
                            CH4CEF = 0.000121f,
                            CH4ULL = 0.666667f,
                            CH4UUL = 2.333333f,
                            CO2CEF = 3.11096f,
                            CO2ULL = 0.024548f,
                            CO2UUL = 0.018088f,
                            EmissionPattern = "固定",
                            N2OCEF = 2.4E-05f,
                            N2OULL = 0.666667f,
                            N2OUUL = 2.333333f,
                            Name = "蒸餘油 (燃料油)",
                            Scope = "範疇1",
                            Unit = "L",
                            Year = 0
                        },
                        new
                        {
                            Id = 25,
                            CH4CEF = 2.8E-05f,
                            CH4ULL = 0.7f,
                            CH4UUL = 2f,
                            CO2CEF = 1.752881f,
                            CO2ULL = 0.023772f,
                            CO2UUL = 0.03962f,
                            EmissionPattern = "固定",
                            N2OCEF = 3E-06f,
                            N2OULL = 0.7f,
                            N2OUUL = 2f,
                            Name = "液化石油氣",
                            Scope = "範疇1",
                            Unit = "L",
                            Year = 0
                        },
                        new
                        {
                            Id = 26,
                            CH4CEF = 9.8E-05f,
                            CH4ULL = 0.666667f,
                            CH4UUL = 2.333333f,
                            CO2CEF = 2.393761f,
                            CO2ULL = 0.05457f,
                            CO2UUL = 0.040928f,
                            EmissionPattern = "固定",
                            N2OCEF = 2E-05f,
                            N2OULL = 0.666667f,
                            N2OUUL = 2.333333f,
                            Name = "石油腦",
                            Scope = "範疇1",
                            Unit = "L",
                            Year = 0
                        },
                        new
                        {
                            Id = 27,
                            CH4CEF = 0.000126f,
                            CH4ULL = 0.666667f,
                            CH4UUL = 2.333333f,
                            CO2CEF = 3.378748f,
                            CO2ULL = 0.095415f,
                            CO2UUL = 0.114002f,
                            EmissionPattern = "固定",
                            N2OCEF = 2.5E-05f,
                            N2OULL = 0.666667f,
                            N2OUUL = 2.333333f,
                            Name = "柏油",
                            Scope = "範疇1",
                            Unit = "L",
                            Year = 0
                        },
                        new
                        {
                            Id = 28,
                            CH4CEF = 0.000121f,
                            CH4ULL = 0.666667f,
                            CH4UUL = 2.333333f,
                            CO2CEF = 2.946167f,
                            CO2ULL = 0.0191f,
                            CO2UUL = 0.025921f,
                            EmissionPattern = "固定",
                            N2OCEF = 2.4E-05f,
                            N2OULL = 0.666667f,
                            N2OUUL = 2.333333f,
                            Name = "潤滑油",
                            Scope = "範疇1",
                            Unit = "L",
                            Year = 0
                        },
                        new
                        {
                            Id = 29,
                            CH4CEF = 0.000113f,
                            CH4ULL = 0.666667f,
                            CH4UUL = 2.333333f,
                            CO2CEF = 2.762032f,
                            CO2ULL = 0.015007f,
                            CO2UUL = 0.015007f,
                            EmissionPattern = "固定",
                            N2OCEF = 2.3E-05f,
                            N2OULL = 0.666667f,
                            N2OUUL = 2.333333f,
                            Name = "其他油品",
                            Scope = "範疇1",
                            Unit = "L",
                            Year = 0
                        },
                        new
                        {
                            Id = 30,
                            CH4CEF = 4.6E-05f,
                            CH4ULL = 0.7f,
                            CH4UUL = 2f,
                            CO2CEF = 2.860187f,
                            CO2ULL = 0.082792f,
                            CO2UUL = 0.113636f,
                            EmissionPattern = "固定",
                            N2OCEF = 5E-06f,
                            N2OULL = 0.7f,
                            N2OUUL = 2f,
                            Name = "乙烷",
                            Scope = "範疇1",
                            Unit = "L",
                            Year = 0
                        },
                        new
                        {
                            Id = 31,
                            CH4CEF = 3.3E-05f,
                            CH4ULL = 0.7f,
                            CH4UUL = 2f,
                            CO2CEF = 1.879036f,
                            CO2ULL = 0.032086f,
                            CO2UUL = 0.039216f,
                            EmissionPattern = "固定",
                            N2OCEF = 3E-06f,
                            N2OULL = 0.7f,
                            N2OUUL = 2f,
                            Name = "天然氣",
                            Scope = "範疇1",
                            Unit = "M3",
                            Year = 0
                        },
                        new
                        {
                            Id = 32,
                            CH4CEF = 3.8E-05f,
                            CH4ULL = 0.7f,
                            CH4UUL = 2f,
                            CO2CEF = 2.170437f,
                            CO2ULL = 0.163194f,
                            CO2UUL = 0.197917f,
                            EmissionPattern = "固定",
                            N2OCEF = 4E-06f,
                            N2OULL = 0.7f,
                            N2OUUL = 2f,
                            Name = "煉油氣",
                            Scope = "範疇1",
                            Unit = "M3",
                            Year = 0
                        },
                        new
                        {
                            Id = 33,
                            CH4CEF = 1.8E-05f,
                            CH4ULL = 0.7f,
                            CH4UUL = 2f,
                            CO2CEF = 0.780754f,
                            CO2ULL = 0.15991f,
                            CO2UUL = 0.218468f,
                            EmissionPattern = "固定",
                            N2OCEF = 2E-06f,
                            N2OULL = 0.7f,
                            N2OUUL = 2f,
                            Name = "焦爐氣",
                            Scope = "範疇1",
                            Unit = "M3",
                            Year = 0
                        },
                        new
                        {
                            Id = 34,
                            CH4CEF = 3E-06f,
                            CH4ULL = 0.7f,
                            CH4UUL = 2f,
                            CO2CEF = 0.845817f,
                            CO2ULL = 0.157692f,
                            CO2UUL = 0.184615f,
                            EmissionPattern = "固定",
                            N2OCEF = 0f,
                            N2OULL = 0.7f,
                            N2OUUL = 2f,
                            Name = "高爐氣",
                            Scope = "範疇1",
                            Unit = "M3",
                            Year = 0
                        },
                        new
                        {
                            Id = 35,
                            CH4CEF = 0.000255f,
                            CH4ULL = 0.666667f,
                            CH4UUL = 2.333333f,
                            CO2CEF = 0.779227f,
                            CO2ULL = 0.200654f,
                            CO2UUL = 0.31952f,
                            EmissionPattern = "固定",
                            N2OCEF = 3.4E-05f,
                            N2OULL = 0.625f,
                            N2OUUL = 2.75f,
                            Name = "一般廢棄物",
                            Scope = "範疇1",
                            Unit = "Kg",
                            Year = 0
                        },
                        new
                        {
                            Id = 36,
                            EmissionPattern = "固定",
                            Name = "事業廢棄物",
                            Scope = "範疇1",
                            Unit = "",
                            Year = 0
                        },
                        new
                        {
                            Id = 37,
                            EmissionPattern = "固定",
                            Name = "其他非化石燃料",
                            Scope = "範疇1",
                            Unit = "",
                            Year = 0
                        },
                        new
                        {
                            Id = 38,
                            EmissionPattern = "固定",
                            Name = "木頭－固態",
                            Scope = "範疇1",
                            Unit = "",
                            Year = 0
                        },
                        new
                        {
                            Id = 39,
                            EmissionPattern = "固定",
                            Name = "黑液",
                            Scope = "範疇1",
                            Unit = "",
                            Year = 0
                        },
                        new
                        {
                            Id = 40,
                            EmissionPattern = "固定",
                            Name = "木炭",
                            Scope = "範疇1",
                            Unit = "",
                            Year = 0
                        },
                        new
                        {
                            Id = 41,
                            EmissionPattern = "固定",
                            Name = "其他固體生質燃料",
                            Scope = "範疇1",
                            Unit = "",
                            Year = 0
                        },
                        new
                        {
                            Id = 42,
                            EmissionPattern = "固定",
                            Name = "生質汽油",
                            Scope = "範疇1",
                            Unit = "",
                            Year = 0
                        },
                        new
                        {
                            Id = 43,
                            EmissionPattern = "固定",
                            Name = "生質柴油",
                            Scope = "範疇1",
                            Unit = "",
                            Year = 0
                        },
                        new
                        {
                            Id = 44,
                            EmissionPattern = "固定",
                            Name = "其他液態生質燃料",
                            Scope = "範疇1",
                            Unit = "",
                            Year = 0
                        },
                        new
                        {
                            Id = 45,
                            EmissionPattern = "固定",
                            Name = "掩埋場沼氣",
                            Scope = "範疇1",
                            Unit = "",
                            Year = 0
                        },
                        new
                        {
                            Id = 46,
                            EmissionPattern = "固定",
                            Name = "污泥沼氣",
                            Scope = "範疇1",
                            Unit = "",
                            Year = 0
                        },
                        new
                        {
                            Id = 47,
                            EmissionPattern = "固定",
                            Name = "其他氣態生質燃料",
                            Scope = "範疇1",
                            Unit = "",
                            Year = 0
                        },
                        new
                        {
                            Id = 48,
                            CH4CEF = 9.4E-05f,
                            CH4ULL = 0.666667f,
                            CH4UUL = 2.333333f,
                            CO2CEF = 2.19807f,
                            CO2ULL = 0.035714f,
                            CO2UUL = 0.042857f,
                            EmissionPattern = "移動",
                            N2OCEF = 1.9E-05f,
                            N2OULL = 0.666667f,
                            N2OUUL = 2.333333f,
                            Name = "航空汽油",
                            Scope = "範疇1",
                            Unit = "L",
                            Year = 0
                        },
                        new
                        {
                            Id = 49,
                            CH4CEF = 0.0001f,
                            CH4ULL = 0.666667f,
                            CH4UUL = 2.333333f,
                            CO2CEF = 2.39485f,
                            CO2ULL = 0.025175f,
                            CO2UUL = 0.040559f,
                            EmissionPattern = "移動",
                            N2OCEF = 2E-05f,
                            N2OULL = 0.666667f,
                            N2OUUL = 2.333333f,
                            Name = "航空燃油",
                            Scope = "範疇1",
                            Unit = "L",
                            Year = 0
                        },
                        new
                        {
                            Id = 50,
                            CH4CEF = 0.000816f,
                            CH4ULL = 0.666667f,
                            CH4UUL = 2.44f,
                            CO2CEF = 2.263133f,
                            CO2ULL = 0.025974f,
                            CO2UUL = 0.053391f,
                            EmissionPattern = "移動",
                            N2OCEF = 0.000261f,
                            N2OULL = 0.666667f,
                            N2OUUL = 2.333333f,
                            Name = "車用汽油",
                            Scope = "範疇1",
                            Unit = "L",
                            Year = 0
                        },
                        new
                        {
                            Id = 51,
                            CH4CEF = 0.000137f,
                            CH4ULL = 0.589744f,
                            CH4UUL = 1.435897f,
                            CO2CEF = 2.606032f,
                            CO2ULL = 0.020243f,
                            CO2UUL = 0.009447f,
                            EmissionPattern = "移動",
                            N2OCEF = 0.000137f,
                            N2OULL = 0.666667f,
                            N2OUUL = 2.076923f,
                            Name = "柴油",
                            Scope = "範疇1",
                            Unit = "L",
                            Year = 0
                        },
                        new
                        {
                            Id = 52,
                            CH4CEF = 0.000107f,
                            CH4ULL = 0.666667f,
                            CH4UUL = 2.333333f,
                            CO2CEF = 2.558763f,
                            CO2ULL = 0.015299f,
                            CO2UUL = 0.025035f,
                            EmissionPattern = "移動",
                            N2OCEF = 2.1E-05f,
                            N2OULL = 0.666667f,
                            N2OUUL = 2.333333f,
                            Name = "煤油",
                            Scope = "範疇1",
                            Unit = "L",
                            Year = 0
                        },
                        new
                        {
                            Id = 53,
                            CH4CEF = 0.000121f,
                            CH4ULL = 0.666667f,
                            CH4UUL = 2.333333f,
                            CO2CEF = 2.946167f,
                            CO2ULL = 0.0191f,
                            CO2UUL = 0.025921f,
                            EmissionPattern = "移動",
                            N2OCEF = 2.4E-05f,
                            N2OULL = 0.666667f,
                            N2OUUL = 2.333333f,
                            Name = "潤滑油",
                            Scope = "範疇1",
                            Unit = "L",
                            Year = 0
                        },
                        new
                        {
                            Id = 54,
                            CH4CEF = 0.001722f,
                            CH4ULL = 0f,
                            CH4UUL = 0f,
                            CO2CEF = 1.752881f,
                            CO2ULL = 0.023772f,
                            CO2UUL = 0.03962f,
                            EmissionPattern = "移動",
                            N2OCEF = 6E-06f,
                            N2OULL = 0f,
                            N2OUUL = 0f,
                            Name = "液化石油氣",
                            Scope = "範疇1",
                            Unit = "L",
                            Year = 0
                        },
                        new
                        {
                            Id = 55,
                            CH4CEF = 0.003467f,
                            CH4ULL = 0.456522f,
                            CH4UUL = 15.73913f,
                            CO2CEF = 2.113915f,
                            CO2ULL = 0.032086f,
                            CO2UUL = 0.039216f,
                            EmissionPattern = "移動",
                            N2OCEF = 0.000113f,
                            N2OULL = 0.666667f,
                            N2OUUL = 24.666668f,
                            Name = "液化天然氣",
                            Scope = "範疇1",
                            Unit = "M3",
                            Year = 0
                        },
                        new
                        {
                            Id = 56,
                            CO2CEF = 0.559f,
                            EmissionPattern = "其他電力",
                            Name = "外購電力",
                            Scope = "範疇2",
                            Unit = "",
                            Year = 0
                        },
                        new
                        {
                            Id = 57,
                            CO2CEF = 0.559f,
                            EmissionPattern = "其他電力",
                            Name = "外購電力",
                            Scope = "範疇2",
                            Unit = "",
                            Year = 0
                        },
                        new
                        {
                            Id = 58,
                            CO2CEF = 0.559f,
                            EmissionPattern = "其他電力",
                            Name = "外購電力",
                            Scope = "範疇2",
                            Unit = "",
                            Year = 0
                        },
                        new
                        {
                            Id = 59,
                            CO2CEF = 0.559f,
                            EmissionPattern = "其他電力",
                            Name = "外購電力",
                            Scope = "範疇2",
                            Unit = "",
                            Year = 0
                        },
                        new
                        {
                            Id = 60,
                            CO2CEF = 0.559f,
                            EmissionPattern = "其他電力",
                            Name = "外購電力",
                            Scope = "範疇2",
                            Unit = "",
                            Year = 0
                        },
                        new
                        {
                            Id = 61,
                            CO2CEF = 0.559f,
                            EmissionPattern = "其他電力",
                            Name = "外購電力",
                            Scope = "範疇2",
                            Unit = "",
                            Year = 0
                        },
                        new
                        {
                            Id = 62,
                            CO2CEF = 0.564f,
                            EmissionPattern = "其他電力",
                            Name = "外購電力",
                            Scope = "範疇2",
                            Unit = "",
                            Year = 0
                        },
                        new
                        {
                            Id = 63,
                            CO2CEF = 0.559f,
                            EmissionPattern = "其他電力",
                            Name = "外購電力",
                            Scope = "範疇2",
                            Unit = "",
                            Year = 0
                        },
                        new
                        {
                            Id = 64,
                            CO2CEF = 0.557f,
                            EmissionPattern = "其他電力",
                            Name = "外購電力",
                            Scope = "範疇2",
                            Unit = "",
                            Year = 0
                        },
                        new
                        {
                            Id = 65,
                            CO2CEF = 0.543f,
                            EmissionPattern = "其他電力",
                            Name = "外購電力",
                            Scope = "範疇2",
                            Unit = "",
                            Year = 0
                        },
                        new
                        {
                            Id = 66,
                            CO2CEF = 0.535f,
                            EmissionPattern = "其他電力",
                            Name = "外購電力",
                            Scope = "範疇2",
                            Unit = "",
                            Year = 0
                        },
                        new
                        {
                            Id = 67,
                            CO2CEF = 0.536f,
                            EmissionPattern = "其他電力",
                            Name = "外購電力",
                            Scope = "範疇2",
                            Unit = "",
                            Year = 0
                        },
                        new
                        {
                            Id = 68,
                            CO2CEF = 0.532f,
                            EmissionPattern = "其他電力",
                            Name = "外購電力",
                            Scope = "範疇2",
                            Unit = "",
                            Year = 0
                        },
                        new
                        {
                            Id = 69,
                            CO2CEF = 0.522f,
                            EmissionPattern = "其他電力",
                            Name = "外購電力",
                            Scope = "範疇2",
                            Unit = "",
                            Year = 0
                        },
                        new
                        {
                            Id = 70,
                            CO2CEF = 0.521f,
                            EmissionPattern = "其他電力",
                            Name = "外購電力",
                            Scope = "範疇2",
                            Unit = "",
                            Year = 0
                        },
                        new
                        {
                            Id = 71,
                            CO2CEF = 0.528f,
                            EmissionPattern = "其他電力",
                            Name = "外購電力",
                            Scope = "範疇2",
                            Unit = "",
                            Year = 0
                        },
                        new
                        {
                            Id = 72,
                            CO2CEF = 0.529f,
                            EmissionPattern = "其他電力",
                            Name = "外購電力",
                            Scope = "範疇2",
                            Unit = "",
                            Year = 0
                        },
                        new
                        {
                            Id = 73,
                            CO2CEF = 0.529f,
                            EmissionPattern = "其他電力",
                            Name = "外購電力",
                            Scope = "範疇2",
                            Unit = "",
                            Year = 0
                        },
                        new
                        {
                            Id = 74,
                            CO2CEF = 0.533f,
                            EmissionPattern = "其他電力",
                            Name = "外購電力",
                            Scope = "範疇2",
                            Unit = "",
                            Year = 0
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AreaDevice", b =>
                {
                    b.HasOne("Carbon_inventory_platform.Models.Device", null)
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Carbon_inventory_platform.Models.Area", null)
                        .WithMany()
                        .HasForeignKey("AreasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Carbon_inventory_platform.Models.Area", b =>
                {
                    b.HasOne("Carbon_inventory_platform.Models.Company", "Company")
                        .WithMany("Areas")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Carbon_inventory_platform.Models.Device", b =>
                {
                    b.HasOne("Carbon_inventory_platform.Models.Material", "Material")
                        .WithMany("Devices")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Carbon_inventory_platform.Models.Company", b =>
                {
                    b.Navigation("Areas");
                });

            modelBuilder.Entity("Carbon_inventory_platform.Models.Material", b =>
                {
                    b.Navigation("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
