// <auto-generated />
using System;
using Carbon_inventory_platform.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Carbon_inventory_platform.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231116171151_0.0.1-4")]
    partial class _0014
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Carbon_inventory_platform.Models.Area", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("PostalCode")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.Property<byte>("isDeleted")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("Carbon_inventory_platform.Models.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte>("isDeleted")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Carbon_inventory_platform.Models.DataCorrection", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("dataCorrections");

                    b.HasData(
                        new
                        {
                            id = 1,
                            name = "有外部校正或多組數據佐證者"
                        },
                        new
                        {
                            id = 2,
                            name = "有內部校正或經過會計簽證等證明者"
                        },
                        new
                        {
                            id = 3,
                            name = "未進行儀器校正或未進行紀錄彙整者"
                        });
                });

            modelBuilder.Entity("Carbon_inventory_platform.Models.DataLevel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("dataLevels");

                    b.HasData(
                        new
                        {
                            id = 1,
                            name = "連續監測"
                        },
                        new
                        {
                            id = 2,
                            name = "定期/間歇量測"
                        },
                        new
                        {
                            id = 3,
                            name = "自行/財務推估"
                        });
                });

            modelBuilder.Entity("Carbon_inventory_platform.Models.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AreaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssetNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<float>("CH4")
                        .HasColumnType("real");

                    b.Property<bool>("CH4_Emission")
                        .HasColumnType("bit");

                    b.Property<float>("CO2")
                        .HasColumnType("real");

                    b.Property<bool>("CO2_Emission")
                        .HasColumnType("bit");

                    b.Property<int>("Correction")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dept")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("EmissionPattern")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<float>("Emissions")
                        .HasColumnType("real");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<float>("HFCS")
                        .HasColumnType("real");

                    b.Property<bool>("HFCS_Emission")
                        .HasColumnType("bit");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaterialId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<float>("N2O")
                        .HasColumnType("real");

                    b.Property<bool>("N2O_Emission")
                        .HasColumnType("bit");

                    b.Property<float>("NF3")
                        .HasColumnType("real");

                    b.Property<bool>("NF3_Emission")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<float>("Num")
                        .HasColumnType("real");

                    b.Property<float>("PFCS")
                        .HasColumnType("real");

                    b.Property<bool>("PFCS_Emission")
                        .HasColumnType("bit");

                    b.Property<string>("Provess")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<float>("SF6")
                        .HasColumnType("real");

                    b.Property<bool>("SF6_Emission")
                        .HasColumnType("bit");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<float>("ULL")
                        .HasColumnType("real");

                    b.Property<float>("UUL")
                        .HasColumnType("real");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte>("isDeleted")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("MaterialId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("Carbon_inventory_platform.Models.GWP", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("GWP_Year")
                        .HasColumnType("int");

                    b.Property<float?>("Num")
                        .HasColumnType("real");

                    b.HasKey("Name");

                    b.ToTable("GWPs");

                    b.HasData(
                        new
                        {
                            Name = "CO2",
                            GWP_Year = 2022,
                            Num = 1f
                        },
                        new
                        {
                            Name = "CH4",
                            GWP_Year = 2022,
                            Num = 27.9f
                        },
                        new
                        {
                            Name = "N2O",
                            GWP_Year = 2022,
                            Num = 273f
                        },
                        new
                        {
                            Name = "R-23",
                            GWP_Year = 2022,
                            Num = 14600f
                        },
                        new
                        {
                            Name = "R-32",
                            GWP_Year = 2022,
                            Num = 771f
                        },
                        new
                        {
                            Name = "R-134A",
                            GWP_Year = 2022,
                            Num = 1530f
                        },
                        new
                        {
                            Name = "七氟丙烷",
                            GWP_Year = 2022,
                            Num = 3600f
                        },
                        new
                        {
                            Name = "R-22",
                            GWP_Year = 2022,
                            Num = 1960f
                        },
                        new
                        {
                            Name = "R-410A",
                            GWP_Year = 2022,
                            Num = 2256f
                        },
                        new
                        {
                            Name = "R-600A",
                            GWP_Year = 2022,
                            Num = 0f
                        },
                        new
                        {
                            Name = "NF3",
                            GWP_Year = 2022,
                            Num = 17400f
                        },
                        new
                        {
                            Name = "SF6",
                            GWP_Year = 2022,
                            Num = 24300f
                        });
                });

            modelBuilder.Entity("Carbon_inventory_platform.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("CH4CEF")
                        .HasColumnType("real");

                    b.Property<float>("CH4ULL")
                        .HasColumnType("real");

                    b.Property<float>("CH4UUL")
                        .HasColumnType("real");

                    b.Property<float>("CO2CEF")
                        .HasColumnType("real");

                    b.Property<float>("CO2ULL")
                        .HasColumnType("real");

                    b.Property<float>("CO2UUL")
                        .HasColumnType("real");

                    b.Property<string>("EmissionPattern")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<float>("N2OCEF")
                        .HasColumnType("real");

                    b.Property<float>("N2OULL")
                        .HasColumnType("real");

                    b.Property<float>("N2OUUL")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Materials");

                    b.HasData(
                        new
                        {
                            Id = 20,
                            CH4CEF = 0.000107f,
                            CH4ULL = 0.666667f,
                            CH4UUL = 2.333333f,
                            CO2CEF = 2.558763f,
                            CO2ULL = -0.015299f,
                            CO2UUL = 0.025035f,
                            EmissionPattern = "固定",
                            N2OCEF = 2.1E-05f,
                            N2OULL = 0.666667f,
                            N2OUUL = 2.333333f,
                            Name = "煤油",
                            Scope = "範疇1",
                            Unit = "L",
                            Year = 0
                        },
                        new
                        {
                            Id = 22,
                            CH4CEF = 0.000106f,
                            CH4ULL = 0.666667f,
                            CH4UUL = 2.333333f,
                            CO2CEF = 2.606032f,
                            CO2ULL = -0.020243f,
                            CO2UUL = 0.009447f,
                            EmissionPattern = "固定",
                            N2OCEF = 2.1E-05f,
                            N2OULL = 0.666667f,
                            N2OUUL = 2.333333f,
                            Name = "柴油",
                            Scope = "範疇1",
                            Unit = "L",
                            Year = 0
                        },
                        new
                        {
                            Id = 23,
                            CH4CEF = 9.8E-05f,
                            CH4ULL = 0.666667f,
                            CH4UUL = 2.333333f,
                            CO2CEF = 2.263133f,
                            CO2ULL = -0.025974f,
                            CO2UUL = 0.053391f,
                            EmissionPattern = "固定",
                            N2OCEF = 2E-05f,
                            N2OULL = 0.666667f,
                            N2OUUL = 2.333333f,
                            Name = "車用汽油",
                            Scope = "範疇1",
                            Unit = "L",
                            Year = 0
                        },
                        new
                        {
                            Id = 25,
                            CH4CEF = 2.8E-05f,
                            CH4ULL = 0.7f,
                            CH4UUL = 2f,
                            CO2CEF = 1.752881f,
                            CO2ULL = -0.023772f,
                            CO2UUL = 0.03962f,
                            EmissionPattern = "固定",
                            N2OCEF = 3E-06f,
                            N2OULL = 0.7f,
                            N2OUUL = 2f,
                            Name = "液化石油氣",
                            Scope = "範疇1",
                            Unit = "L",
                            Year = 0
                        },
                        new
                        {
                            Id = 28,
                            CH4CEF = 0.000121f,
                            CH4ULL = 0.666667f,
                            CH4UUL = 2.333333f,
                            CO2CEF = 2.946167f,
                            CO2ULL = -0.0191f,
                            CO2UUL = 0.025921f,
                            EmissionPattern = "固定",
                            N2OCEF = 2.4E-05f,
                            N2OULL = 0.666667f,
                            N2OUUL = 2.333333f,
                            Name = "潤滑油",
                            Scope = "範疇1",
                            Unit = "L",
                            Year = 0
                        },
                        new
                        {
                            Id = 29,
                            CH4CEF = 0.000113f,
                            CH4ULL = 0.666667f,
                            CH4UUL = 2.333333f,
                            CO2CEF = 2.762032f,
                            CO2ULL = -0.015007f,
                            CO2UUL = 0.015007f,
                            EmissionPattern = "固定",
                            N2OCEF = 2.3E-05f,
                            N2OULL = 0.666667f,
                            N2OUUL = 2.333333f,
                            Name = "其他油品",
                            Scope = "範疇1",
                            Unit = "L",
                            Year = 0
                        },
                        new
                        {
                            Id = 30,
                            CH4CEF = 4.6E-05f,
                            CH4ULL = 0.7f,
                            CH4UUL = 2f,
                            CO2CEF = 2.860187f,
                            CO2ULL = -0.082792f,
                            CO2UUL = 0.113636f,
                            EmissionPattern = "固定",
                            N2OCEF = 5E-06f,
                            N2OULL = 0.7f,
                            N2OUUL = 2f,
                            Name = "乙烷",
                            Scope = "範疇1",
                            Unit = "L",
                            Year = 0
                        },
                        new
                        {
                            Id = 50,
                            CH4CEF = 0.000816f,
                            CH4ULL = 0.666667f,
                            CH4UUL = 2.44f,
                            CO2CEF = -2.263133f,
                            CO2ULL = 0.025974f,
                            CO2UUL = 0.053391f,
                            EmissionPattern = "移動",
                            N2OCEF = 0.000261f,
                            N2OULL = 0.666667f,
                            N2OUUL = 2.333333f,
                            Name = "車用汽油",
                            Scope = "範疇1",
                            Unit = "L",
                            Year = 0
                        },
                        new
                        {
                            Id = 51,
                            CH4CEF = 0.000137f,
                            CH4ULL = 0.589744f,
                            CH4UUL = 1.435897f,
                            CO2CEF = 2.606032f,
                            CO2ULL = -0.020243f,
                            CO2UUL = 0.009447f,
                            EmissionPattern = "移動",
                            N2OCEF = 0.000137f,
                            N2OULL = 0.666667f,
                            N2OUUL = 2.076923f,
                            Name = "柴油",
                            Scope = "範疇1",
                            Unit = "L",
                            Year = 0
                        },
                        new
                        {
                            Id = 52,
                            CH4CEF = 0.000107f,
                            CH4ULL = 0.666667f,
                            CH4UUL = 2.333333f,
                            CO2CEF = 2.558763f,
                            CO2ULL = -0.015299f,
                            CO2UUL = 0.025035f,
                            EmissionPattern = "移動",
                            N2OCEF = 2.1E-05f,
                            N2OULL = 0.666667f,
                            N2OUUL = 2.333333f,
                            Name = "煤油",
                            Scope = "範疇1",
                            Unit = "L",
                            Year = 0
                        },
                        new
                        {
                            Id = 53,
                            CH4CEF = 0.000121f,
                            CH4ULL = 0.666667f,
                            CH4UUL = 2.333333f,
                            CO2CEF = 2.946167f,
                            CO2ULL = -0.0191f,
                            CO2UUL = 0.025921f,
                            EmissionPattern = "移動",
                            N2OCEF = 2.4E-05f,
                            N2OULL = 0.666667f,
                            N2OUUL = 2.333333f,
                            Name = "潤滑油",
                            Scope = "範疇1",
                            Unit = "L",
                            Year = 0
                        },
                        new
                        {
                            Id = 54,
                            CH4CEF = 0.001722f,
                            CH4ULL = 0f,
                            CH4UUL = 0f,
                            CO2CEF = 1.752881f,
                            CO2ULL = -0.023772f,
                            CO2UUL = 0.03962f,
                            EmissionPattern = "移動",
                            N2OCEF = 6E-06f,
                            N2OULL = 0f,
                            N2OUUL = 0f,
                            Name = "液化石油氣",
                            Scope = "範疇1",
                            Unit = "L",
                            Year = 0
                        },
                        new
                        {
                            Id = 55,
                            CH4CEF = 0.003467f,
                            CH4ULL = 0.456522f,
                            CH4UUL = 15.73913f,
                            CO2CEF = 2.113915f,
                            CO2ULL = -0.032086f,
                            CO2UUL = 0.039216f,
                            EmissionPattern = "移動",
                            N2OCEF = 0.000113f,
                            N2OULL = 0.666667f,
                            N2OUUL = 24.666668f,
                            Name = "液化天然氣",
                            Scope = "範疇1",
                            Unit = "M3",
                            Year = 0
                        },
                        new
                        {
                            Id = 56,
                            CH4CEF = 0f,
                            CH4ULL = 0f,
                            CH4UUL = 0f,
                            CO2CEF = 0.495f,
                            CO2ULL = -0.07f,
                            CO2UUL = 0.07f,
                            EmissionPattern = "其他電力",
                            N2OCEF = 0f,
                            N2OULL = 0f,
                            N2OUUL = 0f,
                            Name = "外購電力",
                            Scope = "範疇2",
                            Unit = "",
                            Year = 0
                        });
                });

            modelBuilder.Entity("Carbon_inventory_platform.Models.Refrigerant", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Num")
                        .HasColumnType("float");

                    b.HasKey("Name");

                    b.ToTable("refrigerants");

                    b.HasData(
                        new
                        {
                            Name = "家用冷凍、冷藏裝備",
                            Num = 0.0030000000260770321
                        },
                        new
                        {
                            Name = "獨立商用冷凍、冷藏裝備",
                            Num = 0.054999999701976776
                        },
                        new
                        {
                            Name = "中、大型冷凍、冷藏裝備",
                            Num = 0.20000000298023224
                        },
                        new
                        {
                            Name = "交通用冷凍、冷藏裝備",
                            Num = 0.33000001311302185
                        },
                        new
                        {
                            Name = "工業冷凍、冷藏裝備，包括食品加工及冷藏",
                            Num = 0.15999999642372131
                        },
                        new
                        {
                            Name = "冰水機",
                            Num = 0.090000003576278687
                        },
                        new
                        {
                            Name = "住宅及商業建築冷氣機",
                            Num = 0.029999999329447746
                        },
                        new
                        {
                            Name = "移動式空氣清靜機",
                            Num = 0.20000000298023224
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Carbon_inventory_platform.Models.Area", b =>
                {
                    b.HasOne("Carbon_inventory_platform.Models.Company", "Company")
                        .WithMany("Areas")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Carbon_inventory_platform.Models.Device", b =>
                {
                    b.HasOne("Carbon_inventory_platform.Models.Area", "Areas")
                        .WithMany("Devices")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Carbon_inventory_platform.Models.Material", null)
                        .WithMany("Devices")
                        .HasForeignKey("MaterialId");

                    b.Navigation("Areas");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Carbon_inventory_platform.Models.Area", b =>
                {
                    b.Navigation("Devices");
                });

            modelBuilder.Entity("Carbon_inventory_platform.Models.Company", b =>
                {
                    b.Navigation("Areas");
                });

            modelBuilder.Entity("Carbon_inventory_platform.Models.Material", b =>
                {
                    b.Navigation("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
