// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using 碳盤查平台.Models;

#nullable disable

namespace 碳盤查平台.Migrations
{
    [DbContext(typeof(SQLContext))]
    [Migration("20230811030107_AddSeedData")]
    partial class AddSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("碳盤查平台.Models.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeleteTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("PostalCode")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.Property<byte>("isDeleted")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("碳盤查平台.Models.Authorization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FumtionId")
                        .HasColumnType("int");

                    b.Property<int>("GroupsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GroupsId");

                    b.ToTable("Authorization");
                });

            modelBuilder.Entity("碳盤查平台.Models.CH4", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("CEF")
                        .HasColumnType("real");

                    b.Property<float>("UncertaintyLowerLimit")
                        .HasColumnType("real");

                    b.Property<float>("UncertaintyUpperLimit")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("CH4s");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CEF = 2.5E-05f,
                            UncertaintyLowerLimit = 0.7f,
                            UncertaintyUpperLimit = 2f
                        },
                        new
                        {
                            Id = 2,
                            CEF = 2.8E-05f,
                            UncertaintyLowerLimit = 0.7f,
                            UncertaintyUpperLimit = 2f
                        },
                        new
                        {
                            Id = 3,
                            CEF = 2.5E-05f,
                            UncertaintyLowerLimit = 0.7f,
                            UncertaintyUpperLimit = 2f
                        },
                        new
                        {
                            Id = 4,
                            CEF = 3E-05f,
                            UncertaintyLowerLimit = 0.7f,
                            UncertaintyUpperLimit = 2f
                        },
                        new
                        {
                            Id = 5,
                            CEF = 2.8E-05f,
                            UncertaintyLowerLimit = 0.7f,
                            UncertaintyUpperLimit = 2f
                        },
                        new
                        {
                            Id = 6,
                            CEF = 2.5E-05f,
                            UncertaintyLowerLimit = 0.7f,
                            UncertaintyUpperLimit = 2f
                        },
                        new
                        {
                            Id = 7,
                            CEF = 2.1E-05f,
                            UncertaintyLowerLimit = 0.7f,
                            UncertaintyUpperLimit = 2f
                        },
                        new
                        {
                            Id = 8,
                            CEF = 2.3E-05f,
                            UncertaintyLowerLimit = 0.7f,
                            UncertaintyUpperLimit = 2f
                        },
                        new
                        {
                            Id = 9,
                            CEF = 1.2E-05f,
                            UncertaintyLowerLimit = 0.7f,
                            UncertaintyUpperLimit = 2f
                        },
                        new
                        {
                            Id = 10,
                            CEF = 9E-06f,
                            UncertaintyLowerLimit = 0.7f,
                            UncertaintyUpperLimit = 2f
                        },
                        new
                        {
                            Id = 11,
                            CEF = 1E-05f,
                            UncertaintyLowerLimit = 0.7f,
                            UncertaintyUpperLimit = 2f
                        },
                        new
                        {
                            Id = 12,
                            CEF = 1.6E-05f,
                            UncertaintyLowerLimit = 0.7f,
                            UncertaintyUpperLimit = 2f
                        },
                        new
                        {
                            Id = 13,
                            CEF = 2.9E-05f,
                            UncertaintyLowerLimit = 0.7f,
                            UncertaintyUpperLimit = 2f
                        },
                        new
                        {
                            Id = 14,
                            CEF = 0.000103f,
                            UncertaintyLowerLimit = 0.666667f,
                            UncertaintyUpperLimit = 2.333333f
                        },
                        new
                        {
                            Id = 15,
                            CEF = 9.4E-05f,
                            UncertaintyLowerLimit = 0.666667f,
                            UncertaintyUpperLimit = 2.333333f
                        },
                        new
                        {
                            Id = 16,
                            CEF = 0.0001f,
                            UncertaintyLowerLimit = 0.666667f,
                            UncertaintyUpperLimit = 2.333333f
                        },
                        new
                        {
                            Id = 17,
                            CEF = 0.000113f,
                            UncertaintyLowerLimit = 0.666667f,
                            UncertaintyUpperLimit = 2.333333f
                        },
                        new
                        {
                            Id = 18,
                            CEF = 8.3E-05f,
                            UncertaintyLowerLimit = 0.666667f,
                            UncertaintyUpperLimit = 2.333333f
                        },
                        new
                        {
                            Id = 19,
                            CEF = 0.000133f,
                            UncertaintyLowerLimit = 0.666667f,
                            UncertaintyUpperLimit = 2.333333f
                        },
                        new
                        {
                            Id = 20,
                            CEF = 0.000107f,
                            UncertaintyLowerLimit = 0.666667f,
                            UncertaintyUpperLimit = 2.333333f
                        },
                        new
                        {
                            Id = 21,
                            CEF = 0.000108f,
                            UncertaintyLowerLimit = 0.666667f,
                            UncertaintyUpperLimit = 2.333333f
                        },
                        new
                        {
                            Id = 22,
                            CEF = 0.000106f,
                            UncertaintyLowerLimit = 0.666667f,
                            UncertaintyUpperLimit = 2.333333f
                        },
                        new
                        {
                            Id = 23,
                            CEF = 9.8E-05f,
                            UncertaintyLowerLimit = 0.666667f,
                            UncertaintyUpperLimit = 2.333333f
                        },
                        new
                        {
                            Id = 24,
                            CEF = 0.000121f,
                            UncertaintyLowerLimit = 0.666667f,
                            UncertaintyUpperLimit = 2.333333f
                        },
                        new
                        {
                            Id = 25,
                            CEF = 2.8E-05f,
                            UncertaintyLowerLimit = 0.7f,
                            UncertaintyUpperLimit = 2f
                        },
                        new
                        {
                            Id = 26,
                            CEF = 9.8E-05f,
                            UncertaintyLowerLimit = 0.666667f,
                            UncertaintyUpperLimit = 2.333333f
                        },
                        new
                        {
                            Id = 27,
                            CEF = 0.000126f,
                            UncertaintyLowerLimit = 0.666667f,
                            UncertaintyUpperLimit = 2.333333f
                        },
                        new
                        {
                            Id = 28,
                            CEF = 0.000121f,
                            UncertaintyLowerLimit = 0.666667f,
                            UncertaintyUpperLimit = 2.333333f
                        },
                        new
                        {
                            Id = 29,
                            CEF = 0.000113f,
                            UncertaintyLowerLimit = 0.666667f,
                            UncertaintyUpperLimit = 2.333333f
                        },
                        new
                        {
                            Id = 30,
                            CEF = 4.6E-05f,
                            UncertaintyLowerLimit = 0.7f,
                            UncertaintyUpperLimit = 2f
                        },
                        new
                        {
                            Id = 31,
                            CEF = 3.3E-05f,
                            UncertaintyLowerLimit = 0.7f,
                            UncertaintyUpperLimit = 2f
                        },
                        new
                        {
                            Id = 32,
                            CEF = 3.8E-05f,
                            UncertaintyLowerLimit = 0.7f,
                            UncertaintyUpperLimit = 2f
                        },
                        new
                        {
                            Id = 33,
                            CEF = 1.8E-05f,
                            UncertaintyLowerLimit = 0.7f,
                            UncertaintyUpperLimit = 2f
                        },
                        new
                        {
                            Id = 34,
                            CEF = 3E-06f,
                            UncertaintyLowerLimit = 0.7f,
                            UncertaintyUpperLimit = 2f
                        },
                        new
                        {
                            Id = 35,
                            CEF = 0.000255f,
                            UncertaintyLowerLimit = 0.666667f,
                            UncertaintyUpperLimit = 2.333333f
                        },
                        new
                        {
                            Id = 36,
                            CEF = 0f,
                            UncertaintyLowerLimit = 0f,
                            UncertaintyUpperLimit = 0f
                        },
                        new
                        {
                            Id = 37,
                            CEF = 0f,
                            UncertaintyLowerLimit = 0f,
                            UncertaintyUpperLimit = 0f
                        },
                        new
                        {
                            Id = 38,
                            CEF = 0f,
                            UncertaintyLowerLimit = 0f,
                            UncertaintyUpperLimit = 0f
                        },
                        new
                        {
                            Id = 39,
                            CEF = 0f,
                            UncertaintyLowerLimit = 0f,
                            UncertaintyUpperLimit = 0f
                        },
                        new
                        {
                            Id = 40,
                            CEF = 0f,
                            UncertaintyLowerLimit = 0f,
                            UncertaintyUpperLimit = 0f
                        },
                        new
                        {
                            Id = 41,
                            CEF = 0f,
                            UncertaintyLowerLimit = 0f,
                            UncertaintyUpperLimit = 0f
                        },
                        new
                        {
                            Id = 42,
                            CEF = 0f,
                            UncertaintyLowerLimit = 0f,
                            UncertaintyUpperLimit = 0f
                        },
                        new
                        {
                            Id = 43,
                            CEF = 0f,
                            UncertaintyLowerLimit = 0f,
                            UncertaintyUpperLimit = 0f
                        },
                        new
                        {
                            Id = 44,
                            CEF = 0f,
                            UncertaintyLowerLimit = 0f,
                            UncertaintyUpperLimit = 0f
                        },
                        new
                        {
                            Id = 45,
                            CEF = 0f,
                            UncertaintyLowerLimit = 0f,
                            UncertaintyUpperLimit = 0f
                        },
                        new
                        {
                            Id = 46,
                            CEF = 0f,
                            UncertaintyLowerLimit = 0f,
                            UncertaintyUpperLimit = 0f
                        },
                        new
                        {
                            Id = 47,
                            CEF = 0f,
                            UncertaintyLowerLimit = 0f,
                            UncertaintyUpperLimit = 0f
                        },
                        new
                        {
                            Id = 48,
                            CEF = 9.4E-05f,
                            UncertaintyLowerLimit = 0.666667f,
                            UncertaintyUpperLimit = 2.333333f
                        },
                        new
                        {
                            Id = 49,
                            CEF = 0.0001f,
                            UncertaintyLowerLimit = 0.666667f,
                            UncertaintyUpperLimit = 2.333333f
                        },
                        new
                        {
                            Id = 50,
                            CEF = 0.000816f,
                            UncertaintyLowerLimit = 0.666667f,
                            UncertaintyUpperLimit = 2.44f
                        },
                        new
                        {
                            Id = 51,
                            CEF = 0.000137f,
                            UncertaintyLowerLimit = 0.589744f,
                            UncertaintyUpperLimit = 1.435897f
                        },
                        new
                        {
                            Id = 52,
                            CEF = 0.000107f,
                            UncertaintyLowerLimit = 0.666667f,
                            UncertaintyUpperLimit = 2.333333f
                        },
                        new
                        {
                            Id = 53,
                            CEF = 0.000121f,
                            UncertaintyLowerLimit = 0.666667f,
                            UncertaintyUpperLimit = 2.333333f
                        },
                        new
                        {
                            Id = 54,
                            CEF = 0.001722f,
                            UncertaintyLowerLimit = 0f,
                            UncertaintyUpperLimit = 0f
                        },
                        new
                        {
                            Id = 55,
                            CEF = 0.003467f,
                            UncertaintyLowerLimit = 0.456522f,
                            UncertaintyUpperLimit = 15.73913f
                        });
                });

            modelBuilder.Entity("碳盤查平台.Models.CO2", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("CEF")
                        .HasColumnType("real");

                    b.Property<float>("UncertaintyLowerLimit")
                        .HasColumnType("real");

                    b.Property<float>("UncertaintyUpperLimit")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("CO2s");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CEF = 2.33286f,
                            UncertaintyLowerLimit = 0.077167f,
                            UncertaintyUpperLimit = 0.067653f
                        },
                        new
                        {
                            Id = 2,
                            CEF = 2.693285f,
                            UncertaintyLowerLimit = 0.077167f,
                            UncertaintyUpperLimit = 0.067653f
                        },
                        new
                        {
                            Id = 3,
                            CEF = 2.408113f,
                            UncertaintyLowerLimit = 0.077167f,
                            UncertaintyUpperLimit = 0.067653f
                        },
                        new
                        {
                            Id = 4,
                            CEF = 2.922093f,
                            UncertaintyLowerLimit = 0.03764f,
                            UncertaintyUpperLimit = 0.027467f
                        },
                        new
                        {
                            Id = 5,
                            CEF = 2.693285f,
                            UncertaintyLowerLimit = 0.077167f,
                            UncertaintyUpperLimit = 0.067653f
                        },
                        new
                        {
                            Id = 6,
                            CEF = 2.408113f,
                            UncertaintyLowerLimit = 0.053911f,
                            UncertaintyUpperLimit = 0.053911f
                        },
                        new
                        {
                            Id = 7,
                            CEF = 1.971522f,
                            UncertaintyLowerLimit = 0.034339f,
                            UncertaintyUpperLimit = 0.040583f
                        },
                        new
                        {
                            Id = 8,
                            CEF = 2.253168f,
                            UncertaintyLowerLimit = 0.034339f,
                            UncertaintyUpperLimit = 0.040583f
                        },
                        new
                        {
                            Id = 9,
                            CEF = 1.202633f,
                            UncertaintyLowerLimit = 0.1f,
                            UncertaintyUpperLimit = 0.138614f
                        },
                        new
                        {
                            Id = 10,
                            CEF = 0.95287f,
                            UncertaintyLowerLimit = 0.157009f,
                            UncertaintyUpperLimit = 0.168224f
                        },
                        new
                        {
                            Id = 11,
                            CEF = 1.035387f,
                            UncertaintyLowerLimit = 0.056604f,
                            UncertaintyUpperLimit = 0.018868f
                        },
                        new
                        {
                            Id = 12,
                            CEF = 1.551209f,
                            UncertaintyLowerLimit = 0.104615f,
                            UncertaintyUpperLimit = 0.117949f
                        },
                        new
                        {
                            Id = 13,
                            CEF = 3.135913f,
                            UncertaintyLowerLimit = 0.105607f,
                            UncertaintyUpperLimit = 0.11215f
                        },
                        new
                        {
                            Id = 14,
                            CEF = 3.347347f,
                            UncertaintyLowerLimit = 0.149744f,
                            UncertaintyUpperLimit = 0.179487f
                        },
                        new
                        {
                            Id = 15,
                            CEF = 2.19807f,
                            UncertaintyLowerLimit = 0.035714f,
                            UncertaintyUpperLimit = 0.042857f
                        },
                        new
                        {
                            Id = 16,
                            CEF = 2.39485f,
                            UncertaintyLowerLimit = 0.025175f,
                            UncertaintyUpperLimit = 0.040559f
                        },
                        new
                        {
                            Id = 17,
                            CEF = 2.762032f,
                            UncertaintyLowerLimit = 0.030014f,
                            UncertaintyUpperLimit = 0.030014f
                        },
                        new
                        {
                            Id = 18,
                            CEF = 2.119027f,
                            UncertaintyLowerLimit = 0.1f,
                            UncertaintyUpperLimit = 0.109091f
                        },
                        new
                        {
                            Id = 19,
                            CEF = 2.839525f,
                            UncertaintyLowerLimit = 0.0919f,
                            UncertaintyUpperLimit = 0.096573f
                        },
                        new
                        {
                            Id = 20,
                            CEF = 2.558763f,
                            UncertaintyLowerLimit = 0.015299f,
                            UncertaintyUpperLimit = 0.025035f
                        },
                        new
                        {
                            Id = 21,
                            CEF = 2.794563f,
                            UncertaintyLowerLimit = 0.075034f,
                            UncertaintyUpperLimit = 0.080491f
                        },
                        new
                        {
                            Id = 22,
                            CEF = 2.606032f,
                            UncertaintyLowerLimit = 0.020243f,
                            UncertaintyUpperLimit = 0.009447f
                        },
                        new
                        {
                            Id = 23,
                            CEF = 2.263133f,
                            UncertaintyLowerLimit = 0.025974f,
                            UncertaintyUpperLimit = 0.053391f
                        },
                        new
                        {
                            Id = 24,
                            CEF = 3.11096f,
                            UncertaintyLowerLimit = 0.024548f,
                            UncertaintyUpperLimit = 0.018088f
                        },
                        new
                        {
                            Id = 25,
                            CEF = 1.752881f,
                            UncertaintyLowerLimit = 0.023772f,
                            UncertaintyUpperLimit = 0.03962f
                        },
                        new
                        {
                            Id = 26,
                            CEF = 2.393761f,
                            UncertaintyLowerLimit = 0.05457f,
                            UncertaintyUpperLimit = 0.040928f
                        },
                        new
                        {
                            Id = 27,
                            CEF = 3.378748f,
                            UncertaintyLowerLimit = 0.095415f,
                            UncertaintyUpperLimit = 0.114002f
                        },
                        new
                        {
                            Id = 28,
                            CEF = 2.946167f,
                            UncertaintyLowerLimit = 0.0191f,
                            UncertaintyUpperLimit = 0.025921f
                        },
                        new
                        {
                            Id = 29,
                            CEF = 2.762032f,
                            UncertaintyLowerLimit = 0.015007f,
                            UncertaintyUpperLimit = 0.015007f
                        },
                        new
                        {
                            Id = 30,
                            CEF = 2.860187f,
                            UncertaintyLowerLimit = 0.082792f,
                            UncertaintyUpperLimit = 0.113636f
                        },
                        new
                        {
                            Id = 31,
                            CEF = 1.879036f,
                            UncertaintyLowerLimit = 0.032086f,
                            UncertaintyUpperLimit = 0.039216f
                        },
                        new
                        {
                            Id = 32,
                            CEF = 2.170437f,
                            UncertaintyLowerLimit = 0.163194f,
                            UncertaintyUpperLimit = 0.197917f
                        },
                        new
                        {
                            Id = 33,
                            CEF = 0.780754f,
                            UncertaintyLowerLimit = 0.15991f,
                            UncertaintyUpperLimit = 0.218468f
                        },
                        new
                        {
                            Id = 34,
                            CEF = 0.845817f,
                            UncertaintyLowerLimit = 0.157692f,
                            UncertaintyUpperLimit = 0.184615f
                        },
                        new
                        {
                            Id = 35,
                            CEF = 0.779227f,
                            UncertaintyLowerLimit = 0.200654f,
                            UncertaintyUpperLimit = 0.31952f
                        },
                        new
                        {
                            Id = 36,
                            CEF = 0f,
                            UncertaintyLowerLimit = 0f,
                            UncertaintyUpperLimit = 0f
                        },
                        new
                        {
                            Id = 37,
                            CEF = 0f,
                            UncertaintyLowerLimit = 0f,
                            UncertaintyUpperLimit = 0f
                        },
                        new
                        {
                            Id = 38,
                            CEF = 0f,
                            UncertaintyLowerLimit = 0f,
                            UncertaintyUpperLimit = 0f
                        },
                        new
                        {
                            Id = 39,
                            CEF = 0f,
                            UncertaintyLowerLimit = 0f,
                            UncertaintyUpperLimit = 0f
                        },
                        new
                        {
                            Id = 40,
                            CEF = 0f,
                            UncertaintyLowerLimit = 0f,
                            UncertaintyUpperLimit = 0f
                        },
                        new
                        {
                            Id = 41,
                            CEF = 0f,
                            UncertaintyLowerLimit = 0f,
                            UncertaintyUpperLimit = 0f
                        },
                        new
                        {
                            Id = 42,
                            CEF = 0f,
                            UncertaintyLowerLimit = 0f,
                            UncertaintyUpperLimit = 0f
                        },
                        new
                        {
                            Id = 43,
                            CEF = 0f,
                            UncertaintyLowerLimit = 0f,
                            UncertaintyUpperLimit = 0f
                        },
                        new
                        {
                            Id = 44,
                            CEF = 0f,
                            UncertaintyLowerLimit = 0f,
                            UncertaintyUpperLimit = 0f
                        },
                        new
                        {
                            Id = 45,
                            CEF = 0f,
                            UncertaintyLowerLimit = 0f,
                            UncertaintyUpperLimit = 0f
                        },
                        new
                        {
                            Id = 46,
                            CEF = 0f,
                            UncertaintyLowerLimit = 0f,
                            UncertaintyUpperLimit = 0f
                        },
                        new
                        {
                            Id = 47,
                            CEF = 0f,
                            UncertaintyLowerLimit = 0f,
                            UncertaintyUpperLimit = 0f
                        },
                        new
                        {
                            Id = 48,
                            CEF = 2.19807f,
                            UncertaintyLowerLimit = 0.035714f,
                            UncertaintyUpperLimit = 0.042857f
                        },
                        new
                        {
                            Id = 49,
                            CEF = 2.39485f,
                            UncertaintyLowerLimit = 0.025175f,
                            UncertaintyUpperLimit = 0.040559f
                        },
                        new
                        {
                            Id = 50,
                            CEF = 2.263133f,
                            UncertaintyLowerLimit = 0.025974f,
                            UncertaintyUpperLimit = 0.053391f
                        },
                        new
                        {
                            Id = 51,
                            CEF = 2.606032f,
                            UncertaintyLowerLimit = 0.020243f,
                            UncertaintyUpperLimit = 0.009447f
                        },
                        new
                        {
                            Id = 52,
                            CEF = 2.558763f,
                            UncertaintyLowerLimit = 0.015299f,
                            UncertaintyUpperLimit = 0.025035f
                        },
                        new
                        {
                            Id = 53,
                            CEF = 2.946167f,
                            UncertaintyLowerLimit = 0.0191f,
                            UncertaintyUpperLimit = 0.025921f
                        },
                        new
                        {
                            Id = 54,
                            CEF = 1.752881f,
                            UncertaintyLowerLimit = 0.023772f,
                            UncertaintyUpperLimit = 0.03962f
                        },
                        new
                        {
                            Id = 55,
                            CEF = 2.113915f,
                            UncertaintyLowerLimit = 0.032086f,
                            UncertaintyUpperLimit = 0.039216f
                        });
                });

            modelBuilder.Entity("碳盤查平台.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeleteTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte>("isDeleted")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("碳盤查平台.Models.Data", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Correction")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeleteTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dept")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<float>("Num")
                        .HasColumnType("real");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte>("isDeleted")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("Datas");
                });

            modelBuilder.Entity("碳盤查平台.Models.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<string>("AssetNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte>("CH4")
                        .HasColumnType("tinyint");

                    b.Property<byte>("CO2")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("DataId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DeleteTime")
                        .HasColumnType("datetime2");

                    b.Property<byte>("HFCS")
                        .HasColumnType("tinyint");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<byte>("N2O")
                        .HasColumnType("tinyint");

                    b.Property<byte>("NF3")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte>("PFCS")
                        .HasColumnType("tinyint");

                    b.Property<string>("Provess")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte>("SF6")
                        .HasColumnType("tinyint");

                    b.Property<byte>("isDeleted")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("DataId")
                        .IsUnique();

                    b.HasIndex("MaterialId")
                        .IsUnique();

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("碳盤查平台.Models.Funtion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AuthorizationId")
                        .HasColumnType("int");

                    b.Property<string>("CMainFunction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CSubFunction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Device")
                        .HasColumnType("tinyint");

                    b.Property<string>("MainFunction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MainFunctionNo")
                        .HasColumnType("int");

                    b.Property<string>("SubFunction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubFunctionNo")
                        .HasColumnType("int");

                    b.Property<byte>("isOption")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("AuthorizationId");

                    b.ToTable("Funtions");
                });

            modelBuilder.Entity("碳盤查平台.Models.Groups", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeleteTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FuntionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("isDefault")
                        .HasColumnType("tinyint");

                    b.Property<byte>("isDeleted")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("FuntionId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("碳盤查平台.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CH4Id")
                        .HasColumnType("int");

                    b.Property<int>("CO2Id")
                        .HasColumnType("int");

                    b.Property<string>("EmissionPattern")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("N2OId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("CH4Id")
                        .IsUnique();

                    b.HasIndex("CO2Id")
                        .IsUnique();

                    b.HasIndex("N2OId")
                        .IsUnique();

                    b.ToTable("Materials");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CH4Id = 1,
                            CO2Id = 1,
                            EmissionPattern = "固定",
                            N2OId = 1,
                            Name = "自產煤",
                            Scope = "範疇1",
                            Unit = "Kg"
                        },
                        new
                        {
                            Id = 2,
                            CH4Id = 2,
                            CO2Id = 2,
                            EmissionPattern = "固定",
                            N2OId = 2,
                            Name = "原料煤",
                            Scope = "範疇1",
                            Unit = "Kg"
                        },
                        new
                        {
                            Id = 3,
                            CH4Id = 3,
                            CO2Id = 3,
                            EmissionPattern = "固定",
                            N2OId = 3,
                            Name = "燃料煤",
                            Scope = "範疇1",
                            Unit = "Kg"
                        },
                        new
                        {
                            Id = 4,
                            CH4Id = 4,
                            CO2Id = 4,
                            EmissionPattern = "固定",
                            N2OId = 4,
                            Name = "無煙煤",
                            Scope = "範疇1",
                            Unit = "Kg"
                        },
                        new
                        {
                            Id = 5,
                            CH4Id = 5,
                            CO2Id = 5,
                            EmissionPattern = "固定",
                            N2OId = 5,
                            Name = "焦煤",
                            Scope = "範疇1",
                            Unit = "Kg"
                        },
                        new
                        {
                            Id = 6,
                            CH4Id = 6,
                            CO2Id = 6,
                            EmissionPattern = "固定",
                            N2OId = 6,
                            Name = "煙煤",
                            Scope = "範疇1",
                            Unit = "Kg"
                        },
                        new
                        {
                            Id = 7,
                            CH4Id = 7,
                            CO2Id = 7,
                            EmissionPattern = "固定",
                            N2OId = 7,
                            Name = "亞煙煤(發電)",
                            Scope = "範疇1",
                            Unit = "Kg"
                        },
                        new
                        {
                            Id = 8,
                            CH4Id = 8,
                            CO2Id = 8,
                            EmissionPattern = "固定",
                            N2OId = 8,
                            Name = "亞煙煤(其他)",
                            Scope = "範疇1",
                            Unit = "Kg"
                        },
                        new
                        {
                            Id = 9,
                            CH4Id = 9,
                            CO2Id = 9,
                            EmissionPattern = "固定",
                            N2OId = 9,
                            Name = "褐煤",
                            Scope = "範疇1",
                            Unit = "Kg"
                        },
                        new
                        {
                            Id = 10,
                            CH4Id = 10,
                            CO2Id = 10,
                            EmissionPattern = "固定",
                            N2OId = 10,
                            Name = "油頁岩",
                            Scope = "範疇1",
                            Unit = "Kg"
                        },
                        new
                        {
                            Id = 11,
                            CH4Id = 11,
                            CO2Id = 11,
                            EmissionPattern = "固定",
                            N2OId = 11,
                            Name = "泥煤",
                            Scope = "範疇1",
                            Unit = "Kg"
                        },
                        new
                        {
                            Id = 12,
                            CH4Id = 12,
                            CO2Id = 12,
                            EmissionPattern = "固定",
                            N2OId = 12,
                            Name = "煤球",
                            Scope = "範疇1",
                            Unit = "Kg"
                        },
                        new
                        {
                            Id = 13,
                            CH4Id = 13,
                            CO2Id = 13,
                            EmissionPattern = "固定",
                            N2OId = 13,
                            Name = "焦炭",
                            Scope = "範疇1",
                            Unit = "Kg"
                        },
                        new
                        {
                            Id = 14,
                            CH4Id = 14,
                            CO2Id = 14,
                            EmissionPattern = "固定",
                            N2OId = 14,
                            Name = "石油焦",
                            Scope = "範疇1",
                            Unit = "Kg"
                        },
                        new
                        {
                            Id = 15,
                            CH4Id = 15,
                            CO2Id = 15,
                            EmissionPattern = "固定",
                            N2OId = 15,
                            Name = "航空汽油",
                            Scope = "範疇1",
                            Unit = "L"
                        },
                        new
                        {
                            Id = 16,
                            CH4Id = 16,
                            CO2Id = 16,
                            EmissionPattern = "固定",
                            N2OId = 16,
                            Name = "航空燃油",
                            Scope = "範疇1",
                            Unit = "L"
                        },
                        new
                        {
                            Id = 17,
                            CH4Id = 17,
                            CO2Id = 17,
                            EmissionPattern = "固定",
                            N2OId = 17,
                            Name = "原油",
                            Scope = "範疇1",
                            Unit = "L"
                        },
                        new
                        {
                            Id = 18,
                            CH4Id = 18,
                            CO2Id = 18,
                            EmissionPattern = "固定",
                            N2OId = 18,
                            Name = "奧里油",
                            Scope = "範疇1",
                            Unit = "Kg"
                        },
                        new
                        {
                            Id = 19,
                            CH4Id = 19,
                            CO2Id = 19,
                            EmissionPattern = "固定",
                            N2OId = 19,
                            Name = "天然氣凝結油",
                            Scope = "範疇1",
                            Unit = "M3"
                        },
                        new
                        {
                            Id = 20,
                            CH4Id = 20,
                            CO2Id = 20,
                            EmissionPattern = "固定",
                            N2OId = 20,
                            Name = "煤油",
                            Scope = "範疇1",
                            Unit = "L"
                        },
                        new
                        {
                            Id = 21,
                            CH4Id = 21,
                            CO2Id = 21,
                            EmissionPattern = "固定",
                            N2OId = 21,
                            Name = "頁岩油",
                            Scope = "範疇1",
                            Unit = "Kg"
                        },
                        new
                        {
                            Id = 22,
                            CH4Id = 22,
                            CO2Id = 22,
                            EmissionPattern = "固定",
                            N2OId = 22,
                            Name = "柴油",
                            Scope = "範疇1",
                            Unit = "L"
                        },
                        new
                        {
                            Id = 23,
                            CH4Id = 23,
                            CO2Id = 23,
                            EmissionPattern = "固定",
                            N2OId = 23,
                            Name = "車用汽油",
                            Scope = "範疇1",
                            Unit = "L"
                        },
                        new
                        {
                            Id = 24,
                            CH4Id = 24,
                            CO2Id = 24,
                            EmissionPattern = "固定",
                            N2OId = 24,
                            Name = "蒸餘油 (燃料油)",
                            Scope = "範疇1",
                            Unit = "L"
                        },
                        new
                        {
                            Id = 25,
                            CH4Id = 25,
                            CO2Id = 25,
                            EmissionPattern = "固定",
                            N2OId = 25,
                            Name = "液化石油氣",
                            Scope = "範疇1",
                            Unit = "L"
                        },
                        new
                        {
                            Id = 26,
                            CH4Id = 26,
                            CO2Id = 26,
                            EmissionPattern = "固定",
                            N2OId = 26,
                            Name = "石油腦",
                            Scope = "範疇1",
                            Unit = "L"
                        },
                        new
                        {
                            Id = 27,
                            CH4Id = 27,
                            CO2Id = 27,
                            EmissionPattern = "固定",
                            N2OId = 27,
                            Name = "柏油",
                            Scope = "範疇1",
                            Unit = "L"
                        },
                        new
                        {
                            Id = 28,
                            CH4Id = 28,
                            CO2Id = 28,
                            EmissionPattern = "固定",
                            N2OId = 28,
                            Name = "潤滑油",
                            Scope = "範疇1",
                            Unit = "L"
                        },
                        new
                        {
                            Id = 29,
                            CH4Id = 29,
                            CO2Id = 29,
                            EmissionPattern = "固定",
                            N2OId = 29,
                            Name = "其他油品",
                            Scope = "範疇1",
                            Unit = "L"
                        },
                        new
                        {
                            Id = 30,
                            CH4Id = 30,
                            CO2Id = 30,
                            EmissionPattern = "固定",
                            N2OId = 30,
                            Name = "乙烷",
                            Scope = "範疇1",
                            Unit = "L"
                        },
                        new
                        {
                            Id = 31,
                            CH4Id = 31,
                            CO2Id = 31,
                            EmissionPattern = "固定",
                            N2OId = 31,
                            Name = "天然氣",
                            Scope = "範疇1",
                            Unit = "M3"
                        },
                        new
                        {
                            Id = 32,
                            CH4Id = 32,
                            CO2Id = 32,
                            EmissionPattern = "固定",
                            N2OId = 32,
                            Name = "煉油氣",
                            Scope = "範疇1",
                            Unit = "M3"
                        },
                        new
                        {
                            Id = 33,
                            CH4Id = 33,
                            CO2Id = 33,
                            EmissionPattern = "固定",
                            N2OId = 33,
                            Name = "焦爐氣",
                            Scope = "範疇1",
                            Unit = "M3"
                        },
                        new
                        {
                            Id = 34,
                            CH4Id = 34,
                            CO2Id = 34,
                            EmissionPattern = "固定",
                            N2OId = 34,
                            Name = "高爐氣",
                            Scope = "範疇1",
                            Unit = "M3"
                        },
                        new
                        {
                            Id = 35,
                            CH4Id = 35,
                            CO2Id = 35,
                            EmissionPattern = "固定",
                            N2OId = 35,
                            Name = "一般廢棄物",
                            Scope = "範疇1",
                            Unit = "Kg"
                        },
                        new
                        {
                            Id = 36,
                            CH4Id = 36,
                            CO2Id = 36,
                            EmissionPattern = "固定",
                            N2OId = 36,
                            Name = "事業廢棄物",
                            Scope = "範疇1",
                            Unit = ""
                        },
                        new
                        {
                            Id = 37,
                            CH4Id = 37,
                            CO2Id = 37,
                            EmissionPattern = "固定",
                            N2OId = 37,
                            Name = "其他非化石燃料",
                            Scope = "範疇1",
                            Unit = ""
                        },
                        new
                        {
                            Id = 38,
                            CH4Id = 38,
                            CO2Id = 38,
                            EmissionPattern = "固定",
                            N2OId = 38,
                            Name = "木頭－固態",
                            Scope = "範疇1",
                            Unit = ""
                        },
                        new
                        {
                            Id = 39,
                            CH4Id = 39,
                            CO2Id = 39,
                            EmissionPattern = "固定",
                            N2OId = 39,
                            Name = "黑液",
                            Scope = "範疇1",
                            Unit = ""
                        },
                        new
                        {
                            Id = 40,
                            CH4Id = 40,
                            CO2Id = 40,
                            EmissionPattern = "固定",
                            N2OId = 40,
                            Name = "木炭",
                            Scope = "範疇1",
                            Unit = ""
                        },
                        new
                        {
                            Id = 41,
                            CH4Id = 41,
                            CO2Id = 41,
                            EmissionPattern = "固定",
                            N2OId = 41,
                            Name = "其他固體生質燃料",
                            Scope = "範疇1",
                            Unit = ""
                        },
                        new
                        {
                            Id = 42,
                            CH4Id = 42,
                            CO2Id = 42,
                            EmissionPattern = "固定",
                            N2OId = 42,
                            Name = "生質汽油",
                            Scope = "範疇1",
                            Unit = ""
                        },
                        new
                        {
                            Id = 43,
                            CH4Id = 43,
                            CO2Id = 43,
                            EmissionPattern = "固定",
                            N2OId = 43,
                            Name = "生質柴油",
                            Scope = "範疇1",
                            Unit = ""
                        },
                        new
                        {
                            Id = 44,
                            CH4Id = 44,
                            CO2Id = 44,
                            EmissionPattern = "固定",
                            N2OId = 44,
                            Name = "其他液態生質燃料",
                            Scope = "範疇1",
                            Unit = ""
                        },
                        new
                        {
                            Id = 45,
                            CH4Id = 45,
                            CO2Id = 45,
                            EmissionPattern = "固定",
                            N2OId = 45,
                            Name = "掩埋場沼氣",
                            Scope = "範疇1",
                            Unit = ""
                        },
                        new
                        {
                            Id = 46,
                            CH4Id = 46,
                            CO2Id = 46,
                            EmissionPattern = "固定",
                            N2OId = 46,
                            Name = "污泥沼氣",
                            Scope = "範疇1",
                            Unit = ""
                        },
                        new
                        {
                            Id = 47,
                            CH4Id = 47,
                            CO2Id = 47,
                            EmissionPattern = "固定",
                            N2OId = 47,
                            Name = "其他氣態生質燃料",
                            Scope = "範疇1",
                            Unit = ""
                        },
                        new
                        {
                            Id = 48,
                            CH4Id = 48,
                            CO2Id = 48,
                            EmissionPattern = "移動",
                            N2OId = 48,
                            Name = "航空汽油",
                            Scope = "範疇1",
                            Unit = "L"
                        },
                        new
                        {
                            Id = 49,
                            CH4Id = 49,
                            CO2Id = 49,
                            EmissionPattern = "移動",
                            N2OId = 49,
                            Name = "航空燃油",
                            Scope = "範疇1",
                            Unit = "L"
                        },
                        new
                        {
                            Id = 50,
                            CH4Id = 50,
                            CO2Id = 50,
                            EmissionPattern = "移動",
                            N2OId = 50,
                            Name = "車用汽油",
                            Scope = "範疇1",
                            Unit = "L"
                        },
                        new
                        {
                            Id = 51,
                            CH4Id = 51,
                            CO2Id = 51,
                            EmissionPattern = "移動",
                            N2OId = 51,
                            Name = "柴油",
                            Scope = "範疇1",
                            Unit = "L"
                        },
                        new
                        {
                            Id = 52,
                            CH4Id = 52,
                            CO2Id = 52,
                            EmissionPattern = "移動",
                            N2OId = 52,
                            Name = "煤油",
                            Scope = "範疇1",
                            Unit = "L"
                        },
                        new
                        {
                            Id = 53,
                            CH4Id = 53,
                            CO2Id = 53,
                            EmissionPattern = "移動",
                            N2OId = 53,
                            Name = "潤滑油",
                            Scope = "範疇1",
                            Unit = "L"
                        },
                        new
                        {
                            Id = 54,
                            CH4Id = 54,
                            CO2Id = 54,
                            EmissionPattern = "移動",
                            N2OId = 54,
                            Name = "液化石油氣",
                            Scope = "範疇1",
                            Unit = "L"
                        },
                        new
                        {
                            Id = 55,
                            CH4Id = 55,
                            CO2Id = 55,
                            EmissionPattern = "移動",
                            N2OId = 55,
                            Name = "液化天然氣",
                            Scope = "範疇1",
                            Unit = "M3"
                        });
                });

            modelBuilder.Entity("碳盤查平台.Models.N2O", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("CEF")
                        .HasColumnType("real");

                    b.Property<float>("UncertaintyLowerLimit")
                        .HasColumnType("real");

                    b.Property<float>("UncertaintyUpperLimit")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("N2Os");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CEF = 3.7E-05f,
                            UncertaintyLowerLimit = 0.666667f,
                            UncertaintyUpperLimit = 2.333333f
                        },
                        new
                        {
                            Id = 2,
                            CEF = 4.3E-05f,
                            UncertaintyLowerLimit = 0.666667f,
                            UncertaintyUpperLimit = 2.333333f
                        },
                        new
                        {
                            Id = 3,
                            CEF = 3.8E-05f,
                            UncertaintyLowerLimit = 0.666667f,
                            UncertaintyUpperLimit = 2.333333f
                        },
                        new
                        {
                            Id = 4,
                            CEF = 4.5E-05f,
                            UncertaintyLowerLimit = 0.666667f,
                            UncertaintyUpperLimit = 2.333333f
                        },
                        new
                        {
                            Id = 5,
                            CEF = 4.3E-05f,
                            UncertaintyLowerLimit = 0.666667f,
                            UncertaintyUpperLimit = 2.333333f
                        },
                        new
                        {
                            Id = 6,
                            CEF = 3.8E-05f,
                            UncertaintyLowerLimit = 0.666667f,
                            UncertaintyUpperLimit = 2.333333f
                        },
                        new
                        {
                            Id = 7,
                            CEF = 3.1E-05f,
                            UncertaintyLowerLimit = 0.666667f,
                            UncertaintyUpperLimit = 2.333333f
                        },
                        new
                        {
                            Id = 8,
                            CEF = 3.5E-05f,
                            UncertaintyLowerLimit = 0.666667f,
                            UncertaintyUpperLimit = 2.333333f
                        },
                        new
                        {
                            Id = 9,
                            CEF = 1.8E-05f,
                            UncertaintyLowerLimit = 0.666667f,
                            UncertaintyUpperLimit = 2.333333f
                        },
                        new
                        {
                            Id = 10,
                            CEF = 1.3E-05f,
                            UncertaintyLowerLimit = 0.666667f,
                            UncertaintyUpperLimit = 2.333333f
                        },
                        new
                        {
                            Id = 11,
                            CEF = 1.5E-05f,
                            UncertaintyLowerLimit = 0.666667f,
                            UncertaintyUpperLimit = 2.333333f
                        },
                        new
                        {
                            Id = 12,
                            CEF = 2.4E-05f,
                            UncertaintyLowerLimit = 0.666667f,
                            UncertaintyUpperLimit = 2.333333f
                        },
                        new
                        {
                            Id = 13,
                            CEF = 4.4E-05f,
                            UncertaintyLowerLimit = 0.666667f,
                            UncertaintyUpperLimit = 2.333333f
                        },
                        new
                        {
                            Id = 14,
                            CEF = 2.1E-05f,
                            UncertaintyLowerLimit = 0.666667f,
                            UncertaintyUpperLimit = 2.333333f
                        },
                        new
                        {
                            Id = 15,
                            CEF = 1.9E-05f,
                            UncertaintyLowerLimit = 0.666667f,
                            UncertaintyUpperLimit = 2.333333f
                        },
                        new
                        {
                            Id = 16,
                            CEF = 2E-05f,
                            UncertaintyLowerLimit = 0.666667f,
                            UncertaintyUpperLimit = 2.333333f
                        },
                        new
                        {
                            Id = 17,
                            CEF = 2.3E-05f,
                            UncertaintyLowerLimit = 0.666667f,
                            UncertaintyUpperLimit = 2.333333f
                        },
                        new
                        {
                            Id = 18,
                            CEF = 1.7E-05f,
                            UncertaintyLowerLimit = 0.666667f,
                            UncertaintyUpperLimit = 2.333333f
                        },
                        new
                        {
                            Id = 19,
                            CEF = 2.7E-05f,
                            UncertaintyLowerLimit = 0.666667f,
                            UncertaintyUpperLimit = 2.333333f
                        },
                        new
                        {
                            Id = 20,
                            CEF = 2.1E-05f,
                            UncertaintyLowerLimit = 0.666667f,
                            UncertaintyUpperLimit = 2.333333f
                        },
                        new
                        {
                            Id = 21,
                            CEF = 2.2E-05f,
                            UncertaintyLowerLimit = 0.666667f,
                            UncertaintyUpperLimit = 2.333333f
                        },
                        new
                        {
                            Id = 22,
                            CEF = 2.1E-05f,
                            UncertaintyLowerLimit = 0.666667f,
                            UncertaintyUpperLimit = 2.333333f
                        },
                        new
                        {
                            Id = 23,
                            CEF = 2E-05f,
                            UncertaintyLowerLimit = 0.666667f,
                            UncertaintyUpperLimit = 2.333333f
                        },
                        new
                        {
                            Id = 24,
                            CEF = 2.4E-05f,
                            UncertaintyLowerLimit = 0.666667f,
                            UncertaintyUpperLimit = 2.333333f
                        },
                        new
                        {
                            Id = 25,
                            CEF = 3E-06f,
                            UncertaintyLowerLimit = 0.7f,
                            UncertaintyUpperLimit = 2f
                        },
                        new
                        {
                            Id = 26,
                            CEF = 2E-05f,
                            UncertaintyLowerLimit = 0.666667f,
                            UncertaintyUpperLimit = 2.333333f
                        },
                        new
                        {
                            Id = 27,
                            CEF = 2.5E-05f,
                            UncertaintyLowerLimit = 0.666667f,
                            UncertaintyUpperLimit = 2.333333f
                        },
                        new
                        {
                            Id = 28,
                            CEF = 2.4E-05f,
                            UncertaintyLowerLimit = 0.666667f,
                            UncertaintyUpperLimit = 2.333333f
                        },
                        new
                        {
                            Id = 29,
                            CEF = 2.3E-05f,
                            UncertaintyLowerLimit = 0.666667f,
                            UncertaintyUpperLimit = 2.333333f
                        },
                        new
                        {
                            Id = 30,
                            CEF = 5E-06f,
                            UncertaintyLowerLimit = 0.7f,
                            UncertaintyUpperLimit = 2f
                        },
                        new
                        {
                            Id = 31,
                            CEF = 3E-06f,
                            UncertaintyLowerLimit = 0.7f,
                            UncertaintyUpperLimit = 2f
                        },
                        new
                        {
                            Id = 32,
                            CEF = 4E-06f,
                            UncertaintyLowerLimit = 0.7f,
                            UncertaintyUpperLimit = 2f
                        },
                        new
                        {
                            Id = 33,
                            CEF = 2E-06f,
                            UncertaintyLowerLimit = 0.7f,
                            UncertaintyUpperLimit = 2f
                        },
                        new
                        {
                            Id = 34,
                            CEF = 0f,
                            UncertaintyLowerLimit = 0.7f,
                            UncertaintyUpperLimit = 2f
                        },
                        new
                        {
                            Id = 35,
                            CEF = 3.4E-05f,
                            UncertaintyLowerLimit = 0.625f,
                            UncertaintyUpperLimit = 2.75f
                        },
                        new
                        {
                            Id = 36,
                            CEF = 0f,
                            UncertaintyLowerLimit = 0f,
                            UncertaintyUpperLimit = 0f
                        },
                        new
                        {
                            Id = 37,
                            CEF = 0f,
                            UncertaintyLowerLimit = 0f,
                            UncertaintyUpperLimit = 0f
                        },
                        new
                        {
                            Id = 38,
                            CEF = 0f,
                            UncertaintyLowerLimit = 0f,
                            UncertaintyUpperLimit = 0f
                        },
                        new
                        {
                            Id = 39,
                            CEF = 0f,
                            UncertaintyLowerLimit = 0f,
                            UncertaintyUpperLimit = 0f
                        },
                        new
                        {
                            Id = 40,
                            CEF = 0f,
                            UncertaintyLowerLimit = 0f,
                            UncertaintyUpperLimit = 0f
                        },
                        new
                        {
                            Id = 41,
                            CEF = 0f,
                            UncertaintyLowerLimit = 0f,
                            UncertaintyUpperLimit = 0f
                        },
                        new
                        {
                            Id = 42,
                            CEF = 0f,
                            UncertaintyLowerLimit = 0f,
                            UncertaintyUpperLimit = 0f
                        },
                        new
                        {
                            Id = 43,
                            CEF = 0f,
                            UncertaintyLowerLimit = 0f,
                            UncertaintyUpperLimit = 0f
                        },
                        new
                        {
                            Id = 44,
                            CEF = 0f,
                            UncertaintyLowerLimit = 0f,
                            UncertaintyUpperLimit = 0f
                        },
                        new
                        {
                            Id = 45,
                            CEF = 0f,
                            UncertaintyLowerLimit = 0f,
                            UncertaintyUpperLimit = 0f
                        },
                        new
                        {
                            Id = 46,
                            CEF = 0f,
                            UncertaintyLowerLimit = 0f,
                            UncertaintyUpperLimit = 0f
                        },
                        new
                        {
                            Id = 47,
                            CEF = 0f,
                            UncertaintyLowerLimit = 0f,
                            UncertaintyUpperLimit = 0f
                        },
                        new
                        {
                            Id = 48,
                            CEF = 1.9E-05f,
                            UncertaintyLowerLimit = 0.666667f,
                            UncertaintyUpperLimit = 2.333333f
                        },
                        new
                        {
                            Id = 49,
                            CEF = 2E-05f,
                            UncertaintyLowerLimit = 0.666667f,
                            UncertaintyUpperLimit = 2.333333f
                        },
                        new
                        {
                            Id = 50,
                            CEF = 0.000261f,
                            UncertaintyLowerLimit = 0.666667f,
                            UncertaintyUpperLimit = 2.333333f
                        },
                        new
                        {
                            Id = 51,
                            CEF = 0.000137f,
                            UncertaintyLowerLimit = 0.666667f,
                            UncertaintyUpperLimit = 2.076923f
                        },
                        new
                        {
                            Id = 52,
                            CEF = 2.1E-05f,
                            UncertaintyLowerLimit = 0.666667f,
                            UncertaintyUpperLimit = 2.333333f
                        },
                        new
                        {
                            Id = 53,
                            CEF = 2.4E-05f,
                            UncertaintyLowerLimit = 0.666667f,
                            UncertaintyUpperLimit = 2.333333f
                        },
                        new
                        {
                            Id = 54,
                            CEF = 6E-06f,
                            UncertaintyLowerLimit = 0f,
                            UncertaintyUpperLimit = 0f
                        },
                        new
                        {
                            Id = 55,
                            CEF = 0.000113f,
                            UncertaintyLowerLimit = 0.666667f,
                            UncertaintyUpperLimit = 24.666668f
                        });
                });

            modelBuilder.Entity("碳盤查平台.Models.Staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeleteTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Remark")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaffNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte>("isDeleted")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.ToTable("Staffs");
                });

            modelBuilder.Entity("碳盤查平台.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accounts")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeleteTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("GroupsId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Remark")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("TokenCreateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TokenUpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<byte>("isDeleted")
                        .HasColumnType("tinyint");

                    b.Property<byte>("isEnable")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("GroupsId")
                        .IsUnique();

                    b.HasIndex("StaffId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("碳盤查平台.Models.Area", b =>
                {
                    b.HasOne("碳盤查平台.Models.Company", "Company")
                        .WithMany("Areas")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("碳盤查平台.Models.Authorization", b =>
                {
                    b.HasOne("碳盤查平台.Models.Groups", "Groups")
                        .WithMany()
                        .HasForeignKey("GroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Groups");
                });

            modelBuilder.Entity("碳盤查平台.Models.Device", b =>
                {
                    b.HasOne("碳盤查平台.Models.Area", "Area")
                        .WithMany("Devices")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("碳盤查平台.Models.Data", "Data")
                        .WithOne("Device")
                        .HasForeignKey("碳盤查平台.Models.Device", "DataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("碳盤查平台.Models.Material", "Material")
                        .WithOne("Device")
                        .HasForeignKey("碳盤查平台.Models.Device", "MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Data");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("碳盤查平台.Models.Funtion", b =>
                {
                    b.HasOne("碳盤查平台.Models.Authorization", null)
                        .WithMany("Funtions")
                        .HasForeignKey("AuthorizationId");
                });

            modelBuilder.Entity("碳盤查平台.Models.Groups", b =>
                {
                    b.HasOne("碳盤查平台.Models.Funtion", null)
                        .WithMany("Groups")
                        .HasForeignKey("FuntionId");
                });

            modelBuilder.Entity("碳盤查平台.Models.Material", b =>
                {
                    b.HasOne("碳盤查平台.Models.CH4", "CH4")
                        .WithOne("Material")
                        .HasForeignKey("碳盤查平台.Models.Material", "CH4Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("碳盤查平台.Models.CO2", "CO2")
                        .WithOne("Material")
                        .HasForeignKey("碳盤查平台.Models.Material", "CO2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("碳盤查平台.Models.N2O", "N2O")
                        .WithOne("Material")
                        .HasForeignKey("碳盤查平台.Models.Material", "N2OId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CH4");

                    b.Navigation("CO2");

                    b.Navigation("N2O");
                });

            modelBuilder.Entity("碳盤查平台.Models.Staff", b =>
                {
                    b.HasOne("碳盤查平台.Models.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("碳盤查平台.Models.User", b =>
                {
                    b.HasOne("碳盤查平台.Models.Groups", "Groups")
                        .WithOne("User")
                        .HasForeignKey("碳盤查平台.Models.User", "GroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("碳盤查平台.Models.Staff", "Staff")
                        .WithOne("User")
                        .HasForeignKey("碳盤查平台.Models.User", "StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Groups");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("碳盤查平台.Models.Area", b =>
                {
                    b.Navigation("Devices");
                });

            modelBuilder.Entity("碳盤查平台.Models.Authorization", b =>
                {
                    b.Navigation("Funtions");
                });

            modelBuilder.Entity("碳盤查平台.Models.CH4", b =>
                {
                    b.Navigation("Material")
                        .IsRequired();
                });

            modelBuilder.Entity("碳盤查平台.Models.CO2", b =>
                {
                    b.Navigation("Material")
                        .IsRequired();
                });

            modelBuilder.Entity("碳盤查平台.Models.Company", b =>
                {
                    b.Navigation("Areas");
                });

            modelBuilder.Entity("碳盤查平台.Models.Data", b =>
                {
                    b.Navigation("Device")
                        .IsRequired();
                });

            modelBuilder.Entity("碳盤查平台.Models.Funtion", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("碳盤查平台.Models.Groups", b =>
                {
                    b.Navigation("User")
                        .IsRequired();
                });

            modelBuilder.Entity("碳盤查平台.Models.Material", b =>
                {
                    b.Navigation("Device")
                        .IsRequired();
                });

            modelBuilder.Entity("碳盤查平台.Models.N2O", b =>
                {
                    b.Navigation("Material")
                        .IsRequired();
                });

            modelBuilder.Entity("碳盤查平台.Models.Staff", b =>
                {
                    b.Navigation("User")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
